// src/frontend/app/settings/general/docservers/docservers.component.ts
/** This file is part of Open-Capture.

 Open-Capture is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 Open-Capture is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Open-Capture. If not, see <https://www.gnu.org/licenses/gpl-3.0.html>.

 @dev : Nathan Cheval <nathan.cheval@outlook.fr>
 @dev : Oussama Brich <oussama.brich@edissyum.com> */

import { Component, OnInit } from '@angular/core';
import { HttpClient, HttpHeaders } from "@angular/common/http";
import { SettingsService } from "../../../../services/settings.service";
import { AuthService } from "../../../../services/auth.service";
import { ActivatedRoute, Router } from "@angular/router";
import { PrivilegesService } from "../../../../services/privileges.service";
import { LocalStorageService } from "../../../../services/local-storage.service";
import { LastUrlService } from "../../../../services/last-url.service";
import { Sort } from "@angular/material/sort";
import { MAT_FORM_FIELD_DEFAULT_OPTIONS } from "@angular/material/form-field";
import { environment } from  "../../../env";
import { catchError, finalize, tap } from "rxjs/operators";
import { of } from "rxjs";
import { NotificationService } from "../../../../services/notifications/notifications.service";
import { TranslateService } from "@ngx-translate/core";
import { HistoryService } from "../../../../services/history.service";

@Component({
    selector: 'app-docservers',
    templateUrl: './docservers.component.html',
    styleUrls: ['./docservers.component.scss'],
    providers: [
        {provide: MAT_FORM_FIELD_DEFAULT_OPTIONS, useValue: { appearance: 'fill' }},
    ]
})
export class DocserversComponent implements OnInit {
    columnsToDisplay    : string[]      = ['id', 'docserver_id', 'description', 'content', 'actions'];
    headers             : HttpHeaders   = this.authService.headers;
    loading             : boolean       = true;
    updateLoading       : boolean       = false;
    docservers          : any           = [];
    allDocservers       : any           = [];
    pageSize            : number        = 10;
    pageIndex           : number        = 0;
    total               : number        = 0;
    offset              : number        = 0;
    search              : string        = '';

    constructor(
        public router: Router,
        private http: HttpClient,
        private route: ActivatedRoute,
        private authService: AuthService,
        private translate: TranslateService,
        private notify: NotificationService,
        private historyService: HistoryService,
        public serviceSettings: SettingsService,
        private routerExtService: LastUrlService,
        public privilegesService: PrivilegesService,
        private localStorageService: LocalStorageService
    ) { }

    ngOnInit(): void {
        this.serviceSettings.init();

        const lastUrl = this.routerExtService.getPreviousUrl();
        if (lastUrl.includes('settings/general/docservers') || lastUrl === '/') {
            if (this.localStorageService.get('docserversPageIndex'))
                this.pageIndex = parseInt(this.localStorageService.get('docserversPageIndex') as string);
            this.offset = this.pageSize * (this.pageIndex);
        } else
            this.localStorageService.remove('docserversPageIndex');

        this.http.get(environment['url'] + '/ws/config/getDocservers', {headers: this.authService.headers}).pipe(
            tap((data: any) => {
                this.allDocservers = data.docservers;
            }),
            catchError((err: any) => {
                console.debug(err);
                this.notify.handleErrors(err);
                return of(false);
            })
        ).subscribe();
        this.loadDocservers();
    }

    loadDocservers() {
        this.http.get(environment['url'] + '/ws/config/getDocservers?limit=' + this.pageSize + '&offset=' + this.offset + "&search=" + this.search, {headers: this.authService.headers}).pipe(
            tap((data: any) => {
                if (data.docservers[0]) this.total = data.docservers[0].total;
                else if (this.pageIndex !== 0) {
                    this.pageIndex = this.pageIndex - 1;
                    this.offset = this.pageSize * (this.pageIndex);
                    this.loadDocservers();
                }
                this.docservers = data.docservers;
            }),
            finalize(() => this.loading = false),
            catchError((err: any) => {
                console.debug(err);
                this.notify.handleErrors(err);
                return of(false);
            })
        ).subscribe();
    }

    updateValue(event: any, id: number, docserver: string) {
        this.updateLoading = true;
        const value = event.target.value;
        this.docservers.forEach((element: any) => {
            if (element.id === id) {
                element.path = value;
                this.http.put(environment['url'] + '/ws/config/updateDocserver/' + element.id, {'args': element}, {headers: this.authService.headers}).pipe(
                    tap(() => {
                        element.updateMode = false;
                        this.updateLoading = false;
                        this.notify.success(this.translate.instant('DOCSERVERS.docserver_updated'));
                        this.historyService.addHistory('general', 'update_docserver', this.translate.instant('HISTORY-DESC.update_docserver', {docserver: docserver}));
                    }),
                    catchError((err: any) => {
                        console.debug(err);
                        this.notify.handleErrors(err);
                        return of(false);
                    })
                ).subscribe();
            }
        });
    }

    searchDocservers(event: any) {
        this.search = event.target.value;
        this.loadDocservers();
    }

    onPageChange(event: any) {
        this.pageSize = event.pageSize;
        this.offset = this.pageSize * (event.pageIndex);
        this.pageIndex = event.pageIndex;
        this.localStorageService.save('docserversPageIndex', event.pageIndex);
        this.loadDocservers();
    }

    sortData(sort: Sort) {
        const data = this.allDocservers.slice();
        if (!sort.active || sort.direction === '') {
            this.docservers = data.splice(0, this.pageSize);
            return;
        }

        this.docservers = data.sort((a: any, b: any) => {
            const isAsc = sort.direction === 'asc';
            switch (sort.active) {
                case 'id': return this.compare(a.id, b.id, isAsc);
                case 'docserver_id': return this.compare(a.docserver_id, b.docserver_id, isAsc);
                case 'description': return this.compare(a.description, b.description, isAsc);
                default: return 0;
            }
        });
        this.docservers = this.docservers.splice(0, this.pageSize);
    }

    compare(a: number | string, b: number | string, isAsc: boolean) {
        return (a < b ? -1 : 1) * (isAsc ? 1 : -1);
    }
}

<mat-sidenav-container class="absolute left-0 right-0 bottom-0" style="top: 4.1rem">
    <mat-sidenav #sidenav mode="side" opened class="w-1/6 flex flex-col h-full border-r border-green-400" style="top:0.1rem">
        <h3 class="bg-green-400 bg-opacity-60 text-center text-gray-900 m-0 pb-4" style="padding-top: 0.9rem">{{ "SETTINGS.administration" | translate }}</h3>
        <mat-divider class="border-green-400"></mat-divider>
        <mat-nav-list class="pt-0 overflow-x-hidden overflow-y-auto" style="height: calc(100% - 60px)">
            <mat-expansion-panel *ngFor="let parent of this.serviceSettings.getSettingsParent()"
                                 [expanded]="parent.opened" (opened)="this.serviceSettings.closeOtherParent(this.router.url, parent['id'])">
                <mat-expansion-panel-header class="settings_expansion">
                    <mat-panel-title>
                        {{ parent['label'] | translate }}
                    </mat-panel-title>
                </mat-expansion-panel-header>
                <div class="w-full border-t-2 border-gray-600">
                    <div *ngFor="let setting of this.serviceSettings.getSettings()[parent['id']];"
                         [class.border-b]="this.privilegesService.hasPrivilege(setting['privilege']) || setting['privilege'] === '*'"
                         [class.border-gray-400]="this.privilegesService.hasPrivilege(setting['privilege']) || setting['privilege'] === '*'">
                        <div *ngIf="this.serviceSettings.getSettingsAction(parent['id'], setting['id']) else noActions">
                            <mat-expansion-panel *ngIf="this.privilegesService.hasPrivilege(setting['privilege']) || setting['privilege'] === '*'"
                                                 [expanded]="this.router.url.includes(setting['route'])">
                                <mat-expansion-panel-header class="font-normal w-full h-20">
                                    <mat-panel-title class="font-normal justify-center items-center text-center">
                                        <i [class.text-green-400]="this.router.url === setting['route']"
                                           class="absolute text-lg left-4 w-10 h-10 rounded-full flex items-center justify-center {{ setting['icon'] }}">
                                        </i>
                                        <button mat-button [class.text-green-400]="this.router.url === setting['route']"
                                                class="pr-0 ml-2 font-normal w-full h-20 flex justify-center items-center text-center"
                                                (click)="this.serviceSettings.changeSetting(setting['id'], parent['id'])"
                                                routerLink="{{ setting['route'] }}">
                                            <p [class.font-medium]="this.router.url === setting['route']" class="m-0 truncate w-11/12 text-xs 2xl:text-sm">
                                                {{ setting['label'] | translate }}
                                            </p>
                                        </button>
                                    </mat-panel-title>
                                </mat-expansion-panel-header>
                                <div *ngFor="let action of this.serviceSettings.getSettingsAction(parent['id'], setting['id'])"
                                     [class.border-gray-600]="!action['showOnlyIfActive']"
                                     [class.border-t]="!action['showOnlyIfActive']"
                                     [class.w-full]="!action['showOnlyIfActive']">
                                    <div class="border-b border-gray-400"
                                         *ngIf="(this.privilegesService.hasPrivilege(action['privilege']) || setting['privilege'] === '*') && (!action['showOnlyIfActive'] || (action['showOnlyIfActive'] && this.router.url.includes(action['route'])))">
                                        <button mat-button
                                                [class.text-green-400]="this.router.url.includes(action['route'])"
                                                class="font-normal w-full h-12 ml-2 2xl:ml-12 flex items-center text-center"
                                                (click)="this.serviceSettings.changeSetting(setting['id'], parent['id'])"
                                                routerLink="{{ action['route'] }}"
                                                [class.disable_link]="action['showOnlyIfActive']">
                                            <i class="absolute -mt-2.5 2xl:-mt-2 text-lg w-10 h-10 rounded-full flex items-center justify-center {{ action['icon'] }}"></i>
                                            <p class="m-0 ml-10 2xl:ml-12 text-xs 2xl:text-sm" style="margin-top: 2.5px!important">
                                                {{ action['label'] | translate }}
                                            </p>
                                        </button>
                                    </div>
                                </div>
                            </mat-expansion-panel>
                        </div>
                        <ng-template #noActions>
                            <button *ngIf="this.privilegesService.hasPrivilege(setting['privilege']) || setting['privilege'] === '*'"
                                    mat-button [class.text-green-400]="this.router.url === setting['route']"
                                    class="pr-0 ml-2 font-normal w-full h-20 flex justify-center items-center text-center"
                                    (click)="this.serviceSettings.changeSetting(setting['id'], parent['id'])"
                                    routerLink="{{ setting['route'] }}">
                                <i class="absolute -mt-2.5 2xl:-mt-2 left-4 w-10 h-10 rounded-full flex items-center justify-center fa-lg {{ setting['icon'] }}"></i>
                                <p [class.font-medium]="this.router.url === setting['route']" class="m-0 truncate w-11/12 text-xs 2xl:text-sm">
                                    {{ setting['label'] | translate }}
                                </p>
                            </button>
                        </ng-template>
                    </div>
                </div>
            </mat-expansion-panel>
        </mat-nav-list>
    </mat-sidenav>
    <mat-sidenav-content class="bg-white">
        <div *ngIf="this.loading">
            <app-loader></app-loader>
        </div>
        <div class="settings_header">
            <button mat-icon-button (click)="sidenav.toggle(); this.serviceSettings.toggleMenu();"
                    class="absolute left-2 top-2">
                <i [class.fa-arrow-right]="!this.serviceSettings.getIsMenuOpen()" class="fa-solid fa-arrow-left text-2xl text-gray-900"></i>
            </button>
            <div class="settings_title text-center">
                <h3>{{ this.serviceSettings.getTitle() }}</h3>
                <div class="absolute right-4 top-0">
                    <mat-form-field appearance="outline">
                        <mat-label>{{ 'DOCSERVERS.search_docserver' | translate }}</mat-label>
                        <input matInput type="text" [disabled]="this.loading" (keyup)="searchDocservers($event)">
                    </mat-form-field>
                </div>
                <hr class="border-green-400">
            </div>
        </div>
        <div *ngIf="!loading" class="w-full">
            <app-hint [message]="'GLOBAL.dont_touch' | translate"></app-hint>
            <mat-table matSort [dataSource]="docservers" (matSortChange)="sortData($event)">
                <ng-container matColumnDef="id">
                    <mat-header-cell *matHeaderCellDef mat-sort-header="id"> {{ 'HEADER.id' | translate }} </mat-header-cell>
                    <mat-cell *matCellDef="let element"> {{ element.id }} </mat-cell>
                </ng-container>
                <ng-container matColumnDef="docserver_id">
                    <mat-header-cell *matHeaderCellDef mat-sort-header="docserver_id"> {{ 'HEADER.label_short' | translate }} </mat-header-cell>
                    <mat-cell *matCellDef="let element"> {{ element.docserver_id }} </mat-cell>
                </ng-container>
                <ng-container matColumnDef="description">
                    <mat-header-cell *matHeaderCellDef mat-sort-header="description"> {{ 'HEADER.description' | translate }} </mat-header-cell>
                    <mat-cell *matCellDef="let element"> {{ element.description }} </mat-cell>
                </ng-container>
                <ng-container matColumnDef="path">
                    <mat-header-cell *matHeaderCellDef> {{ 'HEADER.path' | translate }} </mat-header-cell>
                    <mat-cell *matCellDef="let element" (click)="element.updateMode = true">
                        <ng-container *ngIf="!element.updateMode else update">
                            {{ element.path }}
                        </ng-container>
                        <ng-template #update>
                            <mat-form-field appearance="outline" class="w-full">
                                <input matInput [value]="element.path" (keyup.enter)="updateValue($event, element.id)"
                                       class="relative -top-2.5" (focusout)="updateValue($event, element.id)">
                            </mat-form-field>
                        </ng-template>
                    </mat-cell>
                </ng-container>
                <ng-container matColumnDef="actions">
                    <mat-header-cell *matHeaderCellDef> </mat-header-cell>
                    <mat-cell *matCellDef="let element">
                        <button *ngIf="!element.updateMode"
                                (click)="element.updateMode = true"
                                matTooltip="{{ 'DOCSERVERS.update' | translate }}" mat-icon-button
                                class="inline-block align-text-top">
                            <i class="fa-solid fa-edit fa-lg"></i>
                        </button>
                        <button *ngIf="element.updateMode"
                                matTooltip="{{ 'CONFIGURATIONS.validate' | translate }}" mat-icon-button
                                class="inline-block align-text-top">
                            <i *ngIf="!this.updateLoading" class="fa-solid fa-check fa-lg"></i>
                            <i *ngIf="this.updateLoading" class="fa-solid fa-circle-notch fa-spin fa-lg"></i>
                        </button>
                    </mat-cell>
                </ng-container>
                <mat-header-row *matHeaderRowDef="columnsToDisplay"></mat-header-row>
                <mat-row *matRowDef="let row; columns: columnsToDisplay;"
                         class="cursor-pointer hover:text-green-400 hover:shadow-md transition-colors duration-300"></mat-row>
            </mat-table>
            <mat-paginator showFirstLastButtons
                           *ngIf="this.total > 0"
                           [length]="this.total"
                           [pageSize]="pageSize"
                           [pageIndex]="pageIndex"
                           [pageSizeOptions]="[5, 10, 15, 20, 50]"
                           (page)="onPageChange($event)">
            </mat-paginator>
        </div>
    </mat-sidenav-content>
</mat-sidenav-container>

// frontend/src/pages/settings/general/docservers.tsx
/** This file is part of Open-Capture.

 Open-Capture is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.
 Open-Capture is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Open-Capture. If not, see <https://www.gnu.org/licenses/gpl-3.0.html>.

 @dev : Nathan CHEVAL <nathan.cheval@edissyum.com> */

import { t } from "i18next";
import { Pen } from "lucide-react";
import { useEffect, useState } from "react";

import { AxiosApiCall } from "../../../services/hooks/AxiosApiCall";
import { showConfirmDialogWithInput } from "../../../services/hooks/ConfirmDialogWithInput";

import Input from "../../../components/Input";
import { Table } from "../../../components/list/Table";
import { showToast } from "../../../components/ToastProvider";


export function SettingsGeneralDocservers() {
    const { get, put } = AxiosApiCall();

    const [loading, setLoading] = useState(false);
    const [docservers, setDocservers] = useState<any>(null);
    const [selectedDocserver, setSelectedDocservers] = useState<any[]>([]);
    const [totalDocserver, setTotalDocservers] = useState<number | null>(null);

    const [searchTerm, setSearchTerm] = useState('');
    const [lazyParams, setLazyParams] = useState({
        first: 0,
        rows: 16,
        page: 0,
        sortField: null as string | null,
        sortOrder: null as 1 | -1 | null
    });
    const [debouncedSearchTerm, setDebouncedSearchTerm] = useState('');

    const columns = [
        { id: 'docserver_id', field: 'docserver_id', header: t('SMTP.login') },
        { id: 'description', field: 'description', header: t('VERIFIER.item_description') },
        { id: 'path', header: t('SECURITY.value'), field: 'path' }
    ];

    const actions = [
        {
            label: t('GLOBAL.modify'),
            icon: <Pen size={ 16 }/>,
            command: () => handleUpdate()
        }
    ];

    const getActionsLine = () => actions;

    // Retrieve docservers
    useEffect(() => {
        const fetchConfigurations = async () => {
            try {
                const response = await get("/config/getDocservers", {
                    params: {
                        limit: lazyParams.rows,
                        offset: lazyParams.first,
                        search: debouncedSearchTerm,
                        filter: lazyParams.sortField,
                        order: lazyParams.sortOrder === 1 ? 'asc' : lazyParams.sortOrder === -1 ? 'desc' : null
                    }
                });
                if (response.docservers) {
                    setDocservers(response.docservers);
                    setTotalDocservers(response.docservers[0]?.total || 0);
                }
            } catch (error) {
                console.error("Error fetching docservers : ", error);
            }
        };

        fetchConfigurations().then();
    }, [lazyParams, debouncedSearchTerm]);

    // Debounce search term
    useEffect(() => {
        const handler = setTimeout(() => {
            setDebouncedSearchTerm(searchTerm);
        }, 500);

        return () => {
            clearTimeout(handler);
        };
    }, [searchTerm]);

    const handleUpdate = () => {
        showConfirmDialogWithInput({
            value: selectedDocserver[0].path,
            title: t('DOCSERVERS.update_docserver_modale'),
            message: t('DOCSERVERS.update_docserver_details', { 'name': selectedDocserver[0].docserver_id }),
            confirmText: t('GLOBAL.modify'),
            cancelText: t('GLOBAL.cancel'),
            onConfirm: (value) => {
                const updateValue = async () => {
                    try {
                        selectedDocserver[0].path = value;
                        await put('/config/updateDocserver/' + selectedDocserver[0].id, selectedDocserver[0]);
                        showToast(t('DOCSERVERS.docserver_updated'), "success");
                        setSelectedDocservers([]);
                        setLoading(false);
                    } catch (error) {
                        setLoading(false);
                        console.error("Error updating docserver : ", error);
                    }
                }
                setLoading(true);
                updateValue().then();
            },
            onCancel: () => {
            }
        });
    };

    return (
        <div className="p-6 bg-(--bg-secondary) h-full w-full flex flex-col flex-1">
            <Input id="search" type="text" name="search" className='bg-(--bg-primary) w-1/5 mb-4' height='h-10' autoFocus
                   value={ searchTerm } placeholder={ t('GLOBAL.search') } onChange={ (e) => setSearchTerm(e.target.value) }/>

            <Table
                columns={ columns }
                loading={ loading }
                pagination={ true }
                actions={ actions }
                data={ docservers }
                lazyParams={ lazyParams }
                actionsLine={ getActionsLine }
                rowsPerPage={ lazyParams.rows }
                skeletonRows={ lazyParams.rows }
                rowsPerPageOptions={ [
                            { "value": 4, "label": "4" },
                            { "value": 8, "label": "8" },
                            { "value": 16, "label": "16" },
                            { "value": 32, "label": "32" }
                        ] }
                selectedRows={ selectedDocserver }
                totalRecords={ totalDocserver || 0 }
                emptyMessage={ t("SECURITY.no_configurations") }
                onLazyParamsChange={ setLazyParams }
                onSelectionChange={ (rows) => setSelectedDocservers(rows) }
            />
        </div>
    );
}
