// src/frontend/app/settings/general/regex/regex.component.ts
/** This file is part of Open-Capture.

 Open-Capture is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 Open-Capture is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Open-Capture. If not, see <https://www.gnu.org/licenses/gpl-3.0.html>.

 @dev : Nathan Cheval <nathan.cheval@outlook.fr> */

import { Component, OnInit } from '@angular/core';
import { Router } from "@angular/router";
import { HttpClient, HttpHeaders } from "@angular/common/http";
import { AuthService } from "../../../../services/auth.service";
import { TranslateService } from "@ngx-translate/core";
import { NotificationService } from "../../../../services/notifications/notifications.service";
import { SettingsService } from "../../../../services/settings.service";
import { PrivilegesService } from "../../../../services/privileges.service";
import { SessionStorageService } from "../../../../services/session-storage.service";
import { environment } from  "../../../env";
import { catchError, finalize, tap } from "rxjs/operators";
import { of } from "rxjs";
import { Sort } from "@angular/material/sort";

@Component({
    selector: 'app-regex',
    templateUrl: './regex.component.html',
    styleUrls: ['./regex.component.scss']
})
export class RegexComponent implements OnInit {
    columnsToDisplay    : string[]      = ['regex_id', 'label', 'content', 'actions'];
    headers             : HttpHeaders   = this.authService.headers;
    loading             : boolean       = true;
    updateLoading       : boolean       = false;
    regex               : any           = [];
    allRegex            : any           = [];
    pageSize            : number        = 10;
    pageIndex           : number        = 0;
    total               : number        = 0;
    offset              : number        = 0;
    search              : string        = '';

    constructor(
        public router: Router,
        private http: HttpClient,
        private authService: AuthService,
        public translate: TranslateService,
        private notify: NotificationService,
        public serviceSettings: SettingsService,
        public privilegesService: PrivilegesService,
        private sessionStorageService: SessionStorageService
    ) { }

    ngOnInit(): void {
        this.serviceSettings.init();

        if (this.sessionStorageService.get('regexPageIndex')) {
            this.pageIndex = parseInt(this.sessionStorageService.get('regexPageIndex') as string);
        }
        this.offset = this.pageSize * (this.pageIndex);

        this.http.get(environment['url'] + '/ws/config/getRegex', {headers: this.authService.headers}).pipe(
            tap((data: any) => {
                this.allRegex = data.regex;
            }),
            catchError((err: any) => {
                console.debug(err);
                this.notify.handleErrors(err);
                return of(false);
            })
        ).subscribe();

        this.loadRegex();
    }

    loadRegex() {
        this.http.get(environment['url'] + '/ws/config/getRegex?limit=' + this.pageSize + '&offset=' + this.offset + "&search=" + this.search, {headers: this.authService.headers}).pipe(
            tap((data: any) => {
                if (data.regex[0]) {
                    this.total = data.regex[0].total;
                } else if (this.pageIndex !== 0) {
                    this.pageIndex = this.pageIndex - 1;
                    this.offset = this.pageSize * (this.pageIndex);
                    this.loadRegex();
                }
                this.regex = data.regex;
            }),
            finalize(() => this.loading = false),
            catchError((err: any) => {
                console.debug(err);
                this.notify.handleErrors(err);
                return of(false);
            })
        ).subscribe();
    }

    updateValue(event: any, id: number) {
        this.updateLoading = true;
        const value = event.target.value;
        this.regex.forEach((element: any) => {
            if (element.id === id) {
                element.content = value;
                this.http.put(environment['url'] + '/ws/config/updateRegex/' + element.id, {'args': element}, {headers: this.authService.headers}).pipe(
                    tap(() => {
                        element.updateMode = false;
                        this.updateLoading = false;
                        this.notify.success(this.translate.instant('REGEX.regex_updated'));
                    }),
                    catchError((err: any) => {
                        console.debug(err);
                        this.notify.handleErrors(err);
                        return of(false);
                    })
                ).subscribe();
            }
        });
    }

    searchRegex(event: any) {
        this.search = event.target.value;
        this.loadRegex();
    }

    onPageChange(event: any) {
        this.pageSize = event.pageSize;
        this.offset = this.pageSize * (event.pageIndex);
        this.pageIndex = event.pageIndex;
        this.sessionStorageService.save('regexPageIndex', event.pageIndex);
        this.loadRegex();
    }

    sortData(sort: Sort) {
        const data = this.allRegex.slice();
        if (!sort.active || sort.direction === '') {
            this.regex = data.splice(0, this.pageSize);
            return;
        }

        this.regex = data.sort((a: any, b: any) => {
            const isAsc = sort.direction === 'asc';
            switch (sort.active) {
                case 'regex_id': return this.compare(a.regex_id, b.regex_id, isAsc);
                case 'label': return this.compare(a.label, b.label, isAsc);
                default: return 0;
            }
        });
        this.regex = this.regex.splice(0, this.pageSize);
    }

    compare(a: number | string, b: number | string, isAsc: boolean) {
        return (a < b ? -1 : 1) * (isAsc ? 1 : -1);
    }

}

<mat-sidenav-container class="absolute left-0 right-0 bottom-0" style="top: 4.1rem">
    <mat-sidenav #sidenav mode="side" opened class="w-1/6 flex flex-col h-full border-r border-green-400" style="top:0.1rem">
        <h3 class="bg-green-400 bg-opacity-60 text-center text-gray-900 m-0 pb-4" style="padding-top: 0.9rem">{{ "SETTINGS.administration" | translate }}</h3>
        <mat-divider class="border-green-400"></mat-divider>
        <mat-nav-list class="pt-0 overflow-x-hidden overflow-y-auto" style="height: calc(100% - 60px)">
            <mat-expansion-panel *ngFor="let parent of this.serviceSettings.getSettingsParent()"
                                 [expanded]="parent.opened" (opened)="this.serviceSettings.closeOtherParent(this.router.url, parent['id'])">
                <mat-expansion-panel-header class="settings_expansion">
                    <mat-panel-title>
                        {{ parent['label'] | translate }}
                    </mat-panel-title>
                </mat-expansion-panel-header>
                <div class="w-full border-t-2 border-gray-600">
                    <div *ngFor="let setting of this.serviceSettings.getSettings()[parent['id']];"
                         [class.border-b]="this.privilegesService.hasPrivilege(setting['privilege']) || setting['privilege'] === '*'"
                         [class.border-gray-400]="this.privilegesService.hasPrivilege(setting['privilege']) || setting['privilege'] === '*'">
                        <div *ngIf="this.serviceSettings.getSettingsAction(parent['id'], setting['id']) else noActions">
                            <mat-expansion-panel *ngIf="this.privilegesService.hasPrivilege(setting['privilege']) || setting['privilege'] === '*'"
                                                 [expanded]="this.router.url.includes(setting['route'])">
                                <mat-expansion-panel-header class="font-normal w-full h-20">
                                    <mat-panel-title class="font-normal justify-center items-center text-center">
                                        <i [class.text-green-400]="this.router.url === setting['route']"
                                           class="absolute text-lg left-4 w-10 h-10 rounded-full flex items-center justify-center {{ setting['icon'] }}">
                                        </i>
                                        <button mat-button [class.text-green-400]="this.router.url === setting['route']"
                                                class="pr-0 ml-2 font-normal w-full h-20 flex justify-center items-center text-center"
                                                (click)="this.serviceSettings.changeSetting(setting['id'], parent['id'])"
                                                [routerLink]="setting['route']">
                                            <p [class.font-medium]="this.router.url === setting['route']" class="m-0 truncate w-11/12 text-xs 2xl:text-sm">
                                                {{ setting['label'] | translate }}
                                            </p>
                                        </button>
                                    </mat-panel-title>
                                </mat-expansion-panel-header>
                                <div *ngFor="let action of this.serviceSettings.getSettingsAction(parent['id'], setting['id'])"
                                     [class.border-gray-600]="!action['showOnlyIfActive']"
                                     [class.border-t]="!action['showOnlyIfActive']"
                                     [class.w-full]="!action['showOnlyIfActive']">
                                    <div class="border-b border-gray-400"
                                         *ngIf="(this.privilegesService.hasPrivilege(action['privilege']) || setting['privilege'] === '*') && (!action['showOnlyIfActive'] || (action['showOnlyIfActive'] && this.router.url.includes(action['route'])))">
                                        <button mat-button
                                                [class.text-green-400]="this.router.url.includes(action['route'])"
                                                class="font-normal w-full h-12 ml-2 2xl:ml-12 flex items-center text-center"
                                                (click)="this.serviceSettings.changeSetting(setting['id'], parent['id'])"
                                                [routerLink]="action['route']"
                                                [class.disable_link]="action['showOnlyIfActive']">
                                            <i class="absolute -mt-2.5 2xl:-mt-2 text-lg w-10 h-10 rounded-full flex items-center justify-center {{ action['icon'] }}"></i>
                                            <p class="m-0 ml-10 2xl:ml-12 text-xs 2xl:text-sm" style="margin-top: 2.5px!important">
                                                {{ action['label'] | translate }}
                                            </p>
                                        </button>
                                    </div>
                                </div>
                            </mat-expansion-panel>
                        </div>
                        <ng-template #noActions>
                            <button *ngIf="this.privilegesService.hasPrivilege(setting['privilege']) || setting['privilege'] === '*'"
                                    mat-button [class.text-green-400]="this.router.url === setting['route']"
                                    class="pr-0 ml-2 font-normal w-full h-20 flex justify-center items-center text-center"
                                    (click)="this.serviceSettings.changeSetting(setting['id'], parent['id'])"
                                    [routerLink]="setting['route']">
                                <i class="absolute -mt-2.5 2xl:-mt-2 left-4 w-10 h-10 rounded-full flex items-center justify-center fa-lg {{ setting['icon'] }}"></i>
                                <p [class.font-medium]="this.router.url === setting['route']" class="m-0 truncate w-11/12 text-xs 2xl:text-sm">
                                    {{ setting['label'] | translate }}
                                </p>
                            </button>
                        </ng-template>
                    </div>
                </div>
            </mat-expansion-panel>
        </mat-nav-list>
    </mat-sidenav>
    <mat-sidenav-content class="bg-white">
        <div *ngIf="this.loading">
            <app-loader></app-loader>
        </div>
        <div class="settings_header">
            <button mat-icon-button (click)="sidenav.toggle();" class="absolute left-2 top-2">
                <i [class.transform]="!sidenav.opened" [class.rotate-180]="!sidenav.opened" class="fa-solid fa-stream text-2xl text-gray-900"></i>
            </button>
            <div class="settings_title text-center">
                <h3>{{ this.serviceSettings.getTitle() }}</h3>
                <div class="absolute right-4 top-0">
                    <mat-form-field appearance="outline">
                        <mat-label>{{ 'REGEX.search_regex' | translate }}</mat-label>
                        <input matInput type="text" [disabled]="this.loading" (keyup)="searchRegex($event)">
                    </mat-form-field>
                </div>
                <hr class="border-green-400">
            </div>
        </div>
        <div *ngIf="!loading" class="w-full">
            <app-hint [message]="'GLOBAL.dont_touch' | translate"></app-hint>
            <mat-table matSort [dataSource]="regex" (matSortChange)="sortData($event)">
                <ng-container matColumnDef="regex_id">
                    <mat-header-cell *matHeaderCellDef mat-sort-header="regex_id"> {{ 'HEADER.id' | translate }} </mat-header-cell>
                    <mat-cell *matCellDef="let element"> {{ element.regex_id }} </mat-cell>
                </ng-container>
                <ng-container matColumnDef="label">
                    <mat-header-cell *matHeaderCellDef mat-sort-header="label"> {{ 'HEADER.label' | translate }} </mat-header-cell>
                    <mat-cell *matCellDef="let element"> {{ element.label }} </mat-cell>
                </ng-container>
                <ng-container matColumnDef="content">
                    <mat-header-cell *matHeaderCellDef> {{ 'HEADER.value' | translate }} </mat-header-cell>
                    <mat-cell *matCellDef="let element" (click)="element.updateMode = true">
                        <ng-container *ngIf="!element.updateMode else update">
                            {{ element.content }}
                        </ng-container>
                        <ng-template #update>
                            <mat-form-field appearance="outline" class="w-full">
                                <input [id]="element.id" matInput [value]="element.content" (keyup.enter)="updateValue($event, element.id, element.regex_id)"
                                       class="relative -top-2.5" (focusout)="updateValue($event, element.id, element.regex_id)">
                            </mat-form-field>
                        </ng-template>
                    </mat-cell>
                </ng-container>
                <ng-container matColumnDef="actions">
                    <mat-header-cell *matHeaderCellDef> </mat-header-cell>
                    <mat-cell *matCellDef="let element">
                        <button *ngIf="!element.updateMode"
                                (click)="element.updateMode = true;"
                                matTooltip="{{ 'REGEX.update' | translate }}" mat-icon-button
                                class="inline-block align-text-top">
                            <i class="fa-solid fa-edit fa-lg"></i>
                        </button>
                        <button *ngIf="element.updateMode"
                                matTooltip="{{ 'CONFIGURATIONS.validate' | translate }}" mat-icon-button
                                class="inline-block align-text-top">
                            <i *ngIf="!this.updateLoading" class="fa-solid fa-check fa-lg"></i>
                            <i *ngIf="this.updateLoading" class="fa-solid fa-circle-notch fa-spin fa-lg"></i>
                        </button>
                    </mat-cell>
                </ng-container>
                <mat-header-row *matHeaderRowDef="columnsToDisplay"></mat-header-row>
                <mat-row *matRowDef="let row; columns: columnsToDisplay;"
                         class="cursor-pointer hover:text-green-400 hover:shadow-md transition-colors duration-300"></mat-row>
            </mat-table>
            <mat-paginator showFirstLastButtons
                           *ngIf="this.total > 0"
                           [length]="this.total"
                           [pageSize]="pageSize"
                           [pageIndex]="pageIndex"
                           [pageSizeOptions]="[5, 10, 15, 20, 50]"
                           (page)="onPageChange($event)">
            </mat-paginator>
        </div>
    </mat-sidenav-content>
</mat-sidenav-container>

// frontend/src/pages/settings/general/regex.tsx
/** This file is part of Open-Capture.

 Open-Capture is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.
 Open-Capture is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Open-Capture. If not, see <https://www.gnu.org/licenses/gpl-3.0.html>.

 @dev : Nathan CHEVAL <nathan.cheval@edissyum.com> */

import { t } from "i18next";
import { Pencil } from "lucide-react";
import { useEffect, useState } from "react";

import { axiosApiCall } from "../../../services/hooks/axiosApiCall";
import { showConfirmDialogWithInput } from "../../../services/hooks/ConfirmDialogWithInput";

import Input from "../../../components/Input";
import { Table } from "../../../components/list/Table";
import { showToast } from "../../../components/ToastProvider";


export function SettingsGeneralRegex() {
    const { get, put } = axiosApiCall();

    const [loading, setLoading] = useState(false);
    const [regex, setRegex] = useState<any>(null);
    const [selectedRegex, setSelectedRegex] = useState<any[]>([]);
    const [totalRegex, setTotalRegex] = useState<number | null>(null);

    const [searchTerm, setSearchTerm] = useState('');
    const [lazyParams, setLazyParams] = useState({
        first: 0,
        rows: 16,
        page: 0,
        sortField: null as string | null,
        sortOrder: null as 1 | -1 | null,
    });
    const [debouncedSearchTerm, setDebouncedSearchTerm] = useState('');

    const actions = [
        {
            label: t('GLOBAL.modify'),
            icon: <Pencil className='mr-1' size={ 16 }/>,
            command: () => handleUpdate()
        }
    ];

    const columns = [
        { id: 'regex_id', field: 'regex_id', header: t('SMTP.login')},
        { id: 'label', field: 'label', header: t('GLOBAL.label')},
        { id: 'content', header: t('SECURITY.value'), field: 'content' }
    ];

    const getActionsLine = () => actions;

    // Retrieve regex
    useEffect(() => {
        const fetchConfigurations = async () => {
            try {
                const response = await get("/config/getRegex", {
                    params: {
                        limit: lazyParams.rows,
                        offset: lazyParams.first,
                        search: debouncedSearchTerm,
                        filter: lazyParams.sortField,
                        order: lazyParams.sortOrder === 1 ? 'asc' : lazyParams.sortOrder === -1 ? 'desc' : null
                    }
                });
                if (response.regex) {
                    setRegex(response.regex);
                    setTotalRegex(response.regex[0]?.total || 0);
                }
            } catch (error) {
                console.error("Error fetching regex:", error);
            }
        };

        fetchConfigurations().then();
    }, [lazyParams, debouncedSearchTerm]);

    // Debounce search term
    useEffect(() => {
        const handler = setTimeout(() => {
            setDebouncedSearchTerm(searchTerm);
        }, 500);

        return () => {
            clearTimeout(handler);
        };
    }, [searchTerm]);

    const handleUpdate = () => {
        showConfirmDialogWithInput({
            value: selectedRegex[0].content,
            title: t('REGEX.update_regex_modale'),
            message: t('REGEX.update_regex_details', { 'name': selectedRegex[0].label }),
            confirmText: t('GLOBAL.modify'),
            cancelText: t('GLOBAL.cancel'),
            onConfirm: (value) => {const updateValue = async () => {
                    try {
                        selectedRegex[0].content = value;
                        await put('/config/updateRegex/' + selectedRegex[0].id, selectedRegex[0]);
                        showToast(t('REGEX.regex_updated'), "success");
                        setSelectedRegex([]);
                    } catch (error) {
                        console.error("Error updating regex : ", error);
                    } finally {
                        setLoading(false);
                    }
                }
                setLoading(true);
                updateValue().then();
            }
        });
    };

    return (
        <div className="p-8 bg-(--bg-secondary) h-full w-full flex flex-col flex-1">
            <Input id="search" type="text" name="search" className='bg-(--bg-primary) w-1/5 mb-4' height={ 'h-10' }
                   value={ searchTerm } placeholder={ t('GLOBAL.search') } noMarginBottom={ true }
                   onChange={ (e) => setSearchTerm(e.target.value) }/>

            <Table
                columns={ columns }
                loading={ loading }
                pagination={ true }
                actions={ actions }
                data={ regex }
                lazyParams={ lazyParams }
                actionsLine={ getActionsLine }
                rowsPerPage={ lazyParams.rows }
                skeletonRows={ lazyParams.rows }
                rowsPerPageOptions={ [4, 8, 16, 32] }
                selectedRows={ selectedRegex }
                totalRecords={ totalRegex || 0 }
                emptyMessage={ t("SECURITY.no_configurations") }
                onLazyParamsChange={ setLazyParams }
                onSelectionChange={ (rows) => setSelectedRegex(rows) }
            />
        </div>
    );
}
