// frontend/src/pages/history.tsx
/** This file is part of Open-Capture.

 Open-Capture is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.
 Open-Capture is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Open-Capture. If not, see <https://www.gnu.org/licenses/gpl-3.0.html>.

 @dev : Nathan CHEVAL <nathan.cheval@edissyum.com> */

import { t } from "i18next";
import DOMPurify from "dompurify";
import { Radio } from "@mantine/core";
import { useEffect, useState } from "react";
import { Activity, ChevronDown, Filter, Package } from "lucide-react";

import { Button } from "../components/Button";
import { Select } from "../components/Select";
import { Table } from "../components/list/Table";

import { axiosApiCall } from "../services/hooks/axiosApiCall";
import { usePersistentState } from "../services/hooks/usePersistentState";

export function HistoryList() {
    const { get } = axiosApiCall();

    const [history, setHistory] = useState<any[]>([]);
    const [totalHistory, setTotalHistory] = useState(0);
    const [displayFilters, setDisplayFilters] = useState(false);
    const [loadingHistory, setLoadingHistory] = useState(false);

    const [open, setOpen] = useState({
        user: true,
        module: true,
        submodule: true
    });

    const listModules = [
        { id: 'general', label: t('SETTINGS.general') },
        { id: 'accounts', label: t('HISTORY.accounts') },
        { id: 'verifier', label: t('HISTORY.verifier') },
        { id: 'splitter', label: t('HISTORY.splitter') }
    ]

    const [listUsers, setListUsers] = useState<any[]>([]);
    const [listSubModules, setListSubModules] = useState<any[]>([]);
    const [selectedUser, setSelectedUser] = usePersistentState<string>('selectedUserHistory', '');
    const [selectedModule, setSelectedModule] = usePersistentState<string>('selectedModuleHistory', '');
    const [selectedSubModule, setSelectedSubModule] = usePersistentState<string>('selectedSubModuleHistory', '');

    const [lazyParams, setLazyParams] = usePersistentState<{
        first: number;
        rows: number;
        page: number;
        sortField: string | null;
        sortOrder: 1 | -1 | null;
    }>('historyLazyParams', {
            first: 0,
            rows: 16,
            page: 0,
            sortField: null,
            sortOrder: null
        }
    );

    const columns: any = [
        { id: 'history_module', field: 'history_module', header: t('MAILCOLLECT.module'), sortable: true, className: 'w-1/12' },
        { id: 'history_submodule', field: 'history_submodule', header: t('HISTORY.submodule'), sortable: true, className: 'w-3/24' },
        { id: 'history_date', field: 'date', header: t('HISTORY.event_date'), sortable: true, className: 'w-3/24' },
        { id: 'user_info', field: 'user_info', header: t('HISTORY.user_info'), className: 'w-2/12' },
        {
            id: 'history_desc',
            field: 'history_desc',
            header: t('HISTORY.description'),
            className: 'w-4/12',
            body: (row: any) => (
                <div className='truncate' title={ row.history_desc }
                     dangerouslySetInnerHTML={ { __html: DOMPurify.sanitize(row.history_desc) } }></div>
            )
        },
        { id: 'user_ip', field: 'user_ip', header: t('HISTORY.ip'), className: 'w-1/12' },
    ];

    // Fetch processes list, submodules and users
    useEffect(() => {
        setLoadingHistory(true);

        const fetchHistory = async () => {
            const res = await get('/history/list', {
                params: {
                    user: selectedUser,
                    limit: lazyParams.rows,
                    module: selectedModule,
                    offset: lazyParams.first,
                    submodule: selectedSubModule,
                    filter: lazyParams.sortField,
                    order: lazyParams.sortOrder === 1 ? 'asc' : lazyParams.sortOrder === -1 ? 'desc' : null
                }
            });

            setHistory(res.history || []);
            if (Object.keys(res.history).length > 0) {
                setTotalHistory(res.history[0].total || 0);
            }
        }

        const fetchSubModules = async () => {
            const res = await get('/history/submodules');
            if (res.history) {
                res.history.forEach((item: any) => {
                    setListSubModules((prev: any) => [...prev, {
                        id: item.history_submodule,
                        label: item.history_submodule
                    }]);
                });
            }
        }

        const fetchUsers = async () => {
            const users = await get('/users/list_full')
            const res = await get('/history/users');
            if (!res.history) return;

            const usersMap = new Map<number, any>();
            res.history.forEach((item: any) => {
                if (!item.user_id) return;

                const user = users.users.find((u: any) => u.id === item.user_id);
                if (!user) return;

                usersMap.set(item.user_id, user);
            });

            setListUsers(Array.from(usersMap.values()));
        }

        fetchUsers().then();
        fetchHistory().then();
        fetchSubModules().then();
        setLoadingHistory(false);
    }, [lazyParams, selectedModule, selectedSubModule, selectedUser]);

    const handleResetFilters = () => {
        setSelectedUser('');
        setSelectedModule('');
        setSelectedSubModule('');
    }

    return (
        <div className='flex h-full bg-(--bg-secondary) w-full overflow-hidden'>
            <div className={ `h-full shrink-0 transition-all border-r-2 border-(--border-secondary)
                            ${ displayFilters ? "w-[300px] opacity-100" : "w-0 opacity-0 z-0" } bg-(--bg-primary)` }>
                <div className='border-b border-(--border-secondary) p-4 flex items-center justify-between gap-2'>
                    <h1 className='text-2xl font-bold'>{ t('VERIFIER.filters') }</h1>
                    <span className='cursor-pointer text-(--text-secondary) hover:text-(--color-primary) whitespace-nowrap'
                          onClick={ handleResetFilters }>
                        { t('VERIFIER.erase_filters') }
                    </span>
                </div>
                <div className='flex flex-col h-full overflow-y-auto'>
                    <div className={ `${ open.user ? 'bg-(--bg-secondary)' : '' } border-b border-(--border-secondary)` }>
                        <div className="p-4 cursor-pointer flex items-center justify-between"
                             onClick={ () => setOpen({ ...open, user: !open.user }) }>
                            <div className="flex items-center gap-2">
                                <Package className="text-(--color-primary)" size={ 20 }/>
                                <h3 className='text-lg font-semibold'>{ t('HISTORY.user') }</h3>
                            </div>
                            <ChevronDown
                                size={ 18 }
                                className={ `transition-transform ${ open.user ? "rotate-180" : "" }` }/>
                        </div>

                        { open.user && (
                            <div className='p-4 pt-0'>
                                <Select
                                    
                                    value={ selectedUser.toString() }
                                    id="folder_destination"
                                    className="w-full mb-2"
                                    label={ t('HISTORY.user') }
                                    options={ listUsers.map((user: any) => ({
                                        label: user.lastname + ' ' + user.firstname + ' (' + user.username + ')',
                                        value: user.id.toString()
                                    })) }
                                    onChange={ (value) => setSelectedUser(value.toString()) }
                                />
                            </div>
                        ) }
                    </div>
                    <div className={ `${ open.module ? 'bg-(--bg-secondary)' : '' } border-b border-(--border-secondary)` }>
                        <div className="p-4 cursor-pointer flex items-center justify-between"
                             onClick={ () => setOpen({ ...open, module: !open.module }) }>
                            <div className="flex items-center gap-2">
                                <Package className="text-(--color-primary)" size={ 20 }/>
                                <h3 className='text-lg font-semibold'>{ t('MAILCOLLECT.module') }</h3>
                            </div>
                            <ChevronDown
                                size={ 18 }
                                className={ `transition-transform ${ open.module ? "rotate-180" : "" }` }/>
                        </div>

                        { open.module && (
                            <div className='p-4 pt-0'>
                                { listModules.map((module: any) => (
                                    <div className='flex items-center gap-2 text-(--text-secondary)' key={ module.id }>
                                        <Radio
                                            id={ module.id }
                                            value={ module.id }
                                            checked={ selectedModule === module.id }
                                            onChange={ (e) => {
                                                setSelectedModule(e.target.value);
                                            } }>
                                        </Radio>
                                        <label htmlFor={ module.id } key={ module.id } className='cursor-pointer whitespace-nowrap'>
                                            { module.label }
                                        </label>
                                    </div>
                                )) }
                            </div>
                        ) }
                    </div>
                    <div className={ `${ open.submodule ? 'bg-(--bg-secondary)' : '' } border-b border-(--border-secondary)` }>
                        <div className="p-4 cursor-pointer flex items-center justify-between"
                             onClick={ () => setOpen({ ...open, submodule: !open.submodule }) }>
                            <div className="flex items-center gap-2">
                                <Package className="text-(--color-primary)" size={ 20 }/>
                                <h3 className='text-lg font-semibold whitespace-nowrap'>{ t('HISTORY.submodule') }</h3>
                            </div>
                            <ChevronDown
                                size={ 18 }
                                className={ `transition-transform ${ open.submodule ? "rotate-180" : "" }` }/>
                        </div>

                        { open.submodule && (
                            <div className='p-4 pt-0'>
                                <Select
                                    
                                    value={ selectedSubModule.toString() }
                                    id="folder_destination"
                                    className="w-full mb-2"
                                    label={ t('HISTORY.submodule') }
                                    options={ listSubModules.map((submodule: any) => ({
                                        label: submodule.label,
                                        value: submodule.id.toString()
                                    })) }
                                    onChange={ (value) => setSelectedSubModule(value.toString()) }
                                />
                            </div>
                        ) }
                    </div>
                </div>
            </div>

            <div className='p-6 h-full w-full flex flex-col flex-1 z-10'>
                <div className='flex items-center gap-6 mb-4'>
                    <Button variant='bg_white_rounded' icon={ <Filter size={ 14 }/> }
                            onClick={ () => setDisplayFilters(!displayFilters) } selected={ displayFilters }>
                        { t('VERIFIER.filters') }
                    </Button>
                    <span className='flex items-center gap-1'>
                        <Activity size={ 16 }/>
                        <span>
                            { t('HISTORY.history') } ({ totalHistory || 0 })
                        </span>
                    </span>
                </div>
                <Table
                    data={ history }
                    pagination={ true }
                    columns={ columns }
                    lazyParams={ lazyParams }
                    loading={ loadingHistory }
                    rowsPerPage={ lazyParams.rows }
                    skeletonRows={ lazyParams.rows }
                    totalRecords={ totalHistory || 0 }
                    rowsPerPageOptions={ [
                            { "value": 4, "label": "4" },
                            { "value": 8, "label": "8" },
                            { "value": 16, "label": "16" },
                            { "value": 32, "label": "32" }
                        ] }
                    emptyMessage={ t("HISTORY.no_history") }
                    onLazyParamsChange={ setLazyParams }
                />
            </div>
        </div>
    );
}

// src/frontend/app/history/history.component.ts
/** This file is part of Open-Capture.

 Open-Capture is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 Open-Capture is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Open-Capture. If not, see <https://www.gnu.org/licenses/gpl-3.0.html>.

 @dev : Nathan Cheval <nathan.cheval@outlook.fr> */

import { Component, OnInit } from '@angular/core';
import { SettingsService } from "../../services/settings.service";
import { TranslateService } from "@ngx-translate/core";
import { FormControl } from "@angular/forms";
import { environment } from  "../env";
import { catchError, finalize, map, startWith, tap } from "rxjs/operators";
import { Observable, of } from "rxjs";
import { HttpClient } from "@angular/common/http";
import { AuthService } from "../../services/auth.service";
import { NotificationService } from "../../services/notifications/notifications.service";
import { Sort } from "@angular/material/sort";
import { DatePipe } from '@angular/common';
import { UserService } from "../../services/user.service";
import * as moment from "moment";

@Component({
    selector: 'app-history',
    templateUrl: './history.component.html',
    styleUrls: ['./history.component.scss'],
    providers: [DatePipe]
})
export class HistoryComponent implements OnInit {
    filteredUsers       : Observable<any> | any;
    columnsToDisplay    : string[] = ['id', 'history_module', 'history_submodule', 'history_date', 'user_info', 'history_desc', 'user_ip'];
    loading             : boolean  = true;
    toHighlight         : string   = '';
    pageSize            : number   = 10;
    pageIndex           : number   = 0;
    total               : number   = 0;
    offset              : number   = 0;
    history             : any;
    users               : any;
    userSelected        : string = '';
    moduleSelected      : string = '';
    subModuleSelected   : string = '';
    form                : any[]    = [
        {
            'id': 'user_id',
            'type': 'autocomplete',
            'label': this.translate.instant('HISTORY.user'),
            'control': new FormControl(),
            'values': []
        },
        {
            'id': 'module',
            'label': this.translate.instant('CUSTOM-FIELDS.module'),
            'type': 'select',
            'control': new FormControl(),
            'values': [
                {
                    'id': 'general',
                    'label': this.translate.instant('HISTORY.general')
                },
                {
                    'id': 'accounts',
                    'label': this.translate.instant('HISTORY.accounts')
                },
                {
                    'id': 'verifier',
                    'label': this.translate.instant('HOME.verifier')
                },
                {
                    'id': 'splitter',
                    'label': this.translate.instant('HOME.splitter')
                }
            ]
        },
        {
            'id': 'submodule',
            'type': 'select',
            'label': this.translate.instant('HISTORY.submodule'),
            'control': new FormControl(),
            'values': []
        },
    ];

    constructor(
        private http: HttpClient,
        private datePipe: DatePipe,
        private userService: UserService,
        private authService: AuthService,
        private notify: NotificationService,
        private translate: TranslateService,
        public serviceSettings: SettingsService
    ) {}

    private _filter(value: any, array: any) {
        if (typeof value === 'string') {
            this.toHighlight = value;
            const filterValue = value.toLowerCase();
            return array.filter((option: any) => option.value.toLowerCase().indexOf(filterValue) !== -1);
        } else {
            return array;
        }
    }

    ngOnInit(): void {
        if (!this.authService.headersExists) {
            this.authService.generateHeaders();
        }

        if (!this.userService.user) {
            this.userService.user = this.userService.getUserFromLocal();
        }

        this.http.get(environment['url'] + '/ws/users/list_full', {headers: this.authService.headers}).pipe(
            tap((data: any) => {
                this.users = [];
                this.form.forEach((element: any) => {
                    if (element.id === 'user_id') {
                        this.http.get(environment['url'] + '/ws/history/users', {headers: this.authService.headers}).pipe(
                            tap((userHistory: any) => {
                                userHistory.history.forEach((_user: any) => {
                                    data.users.forEach((user: any) => {
                                        if (_user.user_id === user.id) {
                                            this.users.push(user);
                                        }
                                    });
                                });
                            }),
                            catchError((err: any) => {
                                console.debug(err);
                                this.notify.handleErrors(err);
                                return of(false);
                            })
                        ).subscribe();
                        this.filteredUsers = element.control.valueChanges
                            .pipe(
                                startWith(''),
                                map(option => option ? this._filter(option, this.users) : this.users)
                            );
                    } else if (element.id === 'submodule') {
                        this.http.get(environment['url'] + '/ws/history/submodules', {headers: this.authService.headers}).pipe(
                            tap((data: any) => {
                                element.values = data['history'];
                            }),
                            catchError((err: any) => {
                                console.debug(err);
                                this.notify.handleErrors(err);
                                return of(false);
                            })
                        ).subscribe();
                    }
                });
            }),
            catchError((err: any) => {
                console.debug(err);
                this.notify.handleErrors(err);
                return of(false);
            })
        ).subscribe();
        this.loadHistory();
    }

    loadHistory() {
        this.http.get(
            environment['url'] + '/ws/history/list?limit=' + this.pageSize + '&offset=' + this.offset + '&user=' + this.userSelected + '&submodule=' + this.subModuleSelected + '&module=' + this.moduleSelected,
            {headers: this.authService.headers}).pipe(
            tap((data: any) => {
                if (data.history[0]) this.total = data.history[0].total;
                this.history = data.history;
                this.form.forEach((element: any) => {
                    if (element.id === 'module') {
                        element.values.forEach((module: any) => {
                            this.history.forEach((history: any) => {
                                if (history.history_module === module.id) {
                                    history.history_module = this.translate.instant(module.label);
                                }
                            });
                        });
                    }
                    if (element.id === 'submodule') {
                        this.http.get(environment['url'] + '/ws/history/submodules?module=' + this.moduleSelected, {headers: this.authService.headers}).pipe(
                            tap((data: any) => {
                                element.values = data['history'];
                            }),
                            catchError((err: any) => {
                                console.debug(err);
                                this.notify.handleErrors(err);
                                return of(false);
                            })
                        ).subscribe();
                    }
                });

                this.history.forEach((element: any) => {
                    const format = moment().localeData().longDateFormat('L');
                    element.history_date = this.datePipe.transform(element.history_date, format + ' HH:mm:ss');
                });
            }),
            finalize(() => {this.loading = false;}),
            catchError((err: any) => {
                console.debug(err);
                this.notify.handleErrors(err);
                return of(false);
            })
        ).subscribe();
    }

    resetPaginator() {
        this.loading = true;
        this.total = 0;
        this.offset = 0;
        this.pageIndex = 0;
    }

    setSelectedUser(userId: any) {
        this.userSelected = userId;
        this.pageIndex = 0;
        this.resetPaginator();
        this.loadHistory();
    }

    setSelectedModule(module: any) {
        this.moduleSelected = module;
        this.resetPaginator();
        this.loadHistory();
    }

    setSelectedSubModule(subModule: any) {
        this.subModuleSelected = subModule;
        this.resetPaginator();
        this.loadHistory();
    }

    resetFilter() {
        this.subModuleSelected = '';
        this.moduleSelected = '';
        this.userSelected = '';
        this.form.forEach((element: any) => {
            element.control.setValue('');
        });
        this.loadHistory();
    }

    onPageChange(event: any) {
        this.pageSize = event.pageSize;
        this.offset = this.pageSize * (event.pageIndex);
        this.loadHistory();
    }

    displayFn(option: any) {
        return option ? option.lastname + ' ' + option.firstname + ' (' + option.username + ')' : '';
    }

    sortData(sort: Sort) {
        const data = this.history.slice();
        if (!sort.active || sort.direction === '') {
            this.history = data;
            return;
        }

        this.history = data.sort((a: any, b: any) => {
            const isAsc = sort.direction === 'asc';
            switch (sort.active) {
                case 'id': return this.compare(a.id, b.id, isAsc);
                case 'history_module': return this.compare(a.history_module, b.history_module, isAsc);
                case 'history_submodule': return this.compare(a.history_submodule, b.history_submodule, isAsc);
                case 'history_date': return this.compare(a.history_date, b.history_date, isAsc);
                case 'user_info': return this.compare(a.user_info, b.user_info, isAsc);
                case 'history_desc': return this.compare(a.history_desc, b.history_desc, isAsc);
                case 'user_ip': return this.compare(a.user_ip, b.user_ip, isAsc);
                default: return 0;
            }
        });
    }

    compare(a: number | string, b: number | string, isAsc: boolean) {
        return (a < b ? -1 : 1) * (isAsc ? 1 : -1);
    }
}

<mat-sidenav-container class="absolute left-0 right-0 bottom-0" style="top: 4.1rem" [autosize]="true">
    <mat-sidenav-content class="bg-white overflow-hidden">
        @if (this.loading) {
            <div>
                <app-loader></app-loader>
            </div>
        }
        <div class="settings_header flex justify-center p-4 items-center bg-green-400 bg-opacity-60 text-gray-900">
            <h3 class="text-center m-0">{{ this.serviceSettings.getTitle() }}</h3>
        </div>
        <hr class="border-green-400 relative z-30">
        <div class="overflow-x-hidden h-full-overflow">
            <div class="flex justify-center">
                <div class="m-auto w-1/12 text-center">{{ 'HISTORY.filter' | translate }} : </div>
                <form class="grid grid-cols-3 gap-6 w-full mt-5 mb-0 text-center">
                    @for (field of this.form; track field['id']) {
                        @if (field['type'] === 'text') {
                            <mat-form-field class="block">
                                <mat-label>{{ field['label'] | translate }}</mat-label>
                                <input matInput [formControl]="field['control']" [type]="field['type']" [placeholder]="field['label'] | translate" [required]="field['required']">
                            </mat-form-field>
                        } @else if (field['type'] === 'autocomplete') {
                            <mat-form-field>
                                <mat-label>{{ field['label'] | translate }}</mat-label>
                                <input matInput [formControl]="field['control']" [type]="field['type']" [matAutocomplete]="autocomplete">
                                @if (field['hint']) {
                                    <mat-hint class="text-gray-600">{{ field['hint'] }}</mat-hint>
                                }
                                <mat-autocomplete #autocomplete="matAutocomplete" [displayWith]="displayFn" (optionSelected)="setSelectedUser($event.option['id'])">
                                    @for (option of this.filteredUsers | async; track option['id']) {
                                        <mat-option [value]="option" [id]="option['id']">
                                            <span [innerHTML]="option['lastname'] + ' ' + option['firstname'] + ' (' + option.username + ')' | highlight: toHighlight"></span>
                                        </mat-option>
                                    }
                                </mat-autocomplete>
                            </mat-form-field>
                        }
                        @if (field['id'] === 'submodule') {
                            <mat-form-field class="block">
                                <mat-label>{{ field['label'] | translate }}</mat-label>
                                <mat-select [formControl]="field['control']" [(value)]="field.control.value" [required]="field['required']" (selectionChange)="setSelectedSubModule($event.value)">
                                    @for (option of field.values; track option['history_submodule']) {
                                        <mat-option [value]="option['history_submodule']">
                                            {{ option['history_submodule'] }}
                                        </mat-option>
                                    }
                                </mat-select>
                            </mat-form-field>
                        }
                        @if (field['id'] === 'module') {
                            <mat-form-field class="block">
                                <mat-label>{{ field['label'] | translate }}</mat-label>
                                <mat-select [formControl]="field['control']" [(value)]="field.control.value"
                                            [required]="field['required']" (selectionChange)="setSelectedModule($event.value)">
                                    @for (option of field.values; track option['id']) {
                                        <mat-option [value]="option['id']">
                                            {{ option['label'] | translate }}
                                        </mat-option>
                                    }
                                </mat-select>
                            </mat-form-field>
                        }
                    }
                </form>
                <div class="m-auto w-1/12 text-center text-xl cursor-pointer" (click)="resetFilter()"
                     [matTooltip]="'HISTORY.refresh_filter' | translate">
                    <i class="fa-solid fa-sync-alt"></i>
                </div>
            </div>
            <hr class="border-green-400 w-1/3 mx-auto my-4">
            <div class="flex justify-center">
                <mat-table matSort [dataSource]="history" (matSortChange)="sortData($event)" class="w-full">
                    <ng-container matColumnDef="id">
                        <mat-header-cell mat-sort-header *matHeaderCellDef style="flex: 0 0 100px!important;">{{ 'HEADER.id' | translate }}</mat-header-cell>
                        <mat-cell *matCellDef="let element" style="flex: 0 0 100px!important;">{{ element.id }}</mat-cell>
                    </ng-container>
                    <ng-container matColumnDef="history_module">
                        <mat-header-cell mat-sort-header *matHeaderCellDef style="flex: 0 0 220px!important;">{{ 'CUSTOM-FIELDS.module' | translate }}</mat-header-cell>
                        <mat-cell *matCellDef="let element" style="flex: 0 0 220px!important;">{{ element['history_module'] }}</mat-cell>
                    </ng-container>
                    <ng-container matColumnDef="history_submodule">
                        <mat-header-cell mat-sort-header *matHeaderCellDef style="flex: 0 0 190px!important;">{{ 'HISTORY.submodule' | translate }}</mat-header-cell>
                        <mat-cell *matCellDef="let element" style="flex: 0 0 190px!important;">{{ element['history_submodule'] }}</mat-cell>
                    </ng-container>
                    <ng-container matColumnDef="history_date">
                        <mat-header-cell mat-sort-header *matHeaderCellDef style="flex: 0 0 220px!important;">{{ 'HISTORY.history_date' | translate }}</mat-header-cell>
                        <mat-cell *matCellDef="let element" style="flex: 0 0 220px!important;">{{ element.date }}</mat-cell>
                    </ng-container>
                    <ng-container matColumnDef="user_info">
                        <mat-header-cell mat-sort-header *matHeaderCellDef style="flex: 0 0 250px!important;">{{ 'HISTORY.user_info' | translate }}</mat-header-cell>
                        <mat-cell *matCellDef="let element" style="flex: 0 0 250px!important;">{{ element['user_info'] }}</mat-cell>
                    </ng-container>
                    <ng-container matColumnDef="history_desc">
                        <mat-header-cell mat-sort-header *matHeaderCellDef>{{ 'HISTORY.history_desc' | translate }}</mat-header-cell>
                        <mat-cell class="p-0.5" *matCellDef="let element" [innerHTML]="'<span>' + element['history_desc'] + '</span>'"></mat-cell>
                    </ng-container>
                    <ng-container matColumnDef="user_ip">
                        <mat-header-cell mat-sort-header *matHeaderCellDef style="flex: 0 0 250px !important">{{ 'HISTORY.user_ip' | translate }}</mat-header-cell>
                        <mat-cell *matCellDef="let element" style="flex: 0 0 250px !important">{{ element['user_ip'] }}</mat-cell>
                    </ng-container>
                    <mat-header-row *matHeaderRowDef="columnsToDisplay"></mat-header-row>
                    <mat-row *matRowDef="let row; columns: columnsToDisplay;"
                             class="hover:text-green-400 select-none hover:shadow-md transition-colors duration-300"></mat-row>
                </mat-table>
            </div>
            <mat-paginator [showFirstLastButtons]="true"
                           [length]="total"
                           [pageSize]="pageSize"
                           [pageIndex]="pageIndex"
                           [pageSizeOptions]="[5, 10, 15, 20, 50]"
                           (page)="onPageChange($event)">
            </mat-paginator>
        </div>
    </mat-sidenav-content>
</mat-sidenav-container>
