// src/frontend/app/home/home.component.ts
/** This file is part of Open-Capture for Invoices.

Open-Capture for Invoices is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Open-Capture is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Open-Capture for Invoices. If not, see <https://www.gnu.org/licenses/gpl-3.0.html>.

@dev : Nathan Cheval <nathan.cheval@outlook.fr> */

import { Component, OnInit } from '@angular/core';
import { AuthService } from "../../services/auth.service";
import { UserService } from "../../services/user.service";
import { LocalStorageService } from "../../services/local-storage.service";
import { PrivilegesService } from "../../services/privileges.service";

@Component({
    selector: 'app-home',
    templateUrl: './home.component.html',
    styleUrls: ['./home.component.scss']
})
export class HomeComponent implements OnInit {
    constructor(
        private authService: AuthService,
        private userService: UserService,
        public privilegesService: PrivilegesService,
        private localeStorageService: LocalStorageService
    ) {
    }

    ngOnInit() {
        this.setValue('');
    }

    setValue(value: string) {
        this.localeStorageService.save('splitter_or_verifier', value);
    }
}

<div class="flex relative justify-center items-center gap-8" style="height: 85vh">
    <mat-card *ngIf="this.privilegesService.hasPrivilege('access_splitter')"
              class="text-center w-full 2xl:w-1/5 lg:w-1/3 sm:w-1/2 shadow-lg transition duration-500 ease-in-out
                     transform hover:-translate-y-1 hover:scale-110 hover:shadow-2xl">
        <a routerLink="/splitter/list" class="block" (click)="setValue('splitter')">
            <div class="bg-splitter bg-no-repeat bg-center w-full h-64 transition duration-500 ease-in-out hover:opacity-30" style="background-size: 20rem"></div>
        </a>
        <div class="absolute inline-flex items-center justify-center w-12 h-10 text-md -right-1 font-bold
                    text-gray-900 bg-green-400 border-4 border-gray-900 rounded-full -top-4">
            {{ getUnseenBatches('splitter') }}
        </div>
        <mat-card-subtitle class="mb-5">
            {{ 'HOME.splitter' | translate }}
        </mat-card-subtitle>
    </mat-card>
    <mat-card *ngIf="this.privilegesService.hasPrivilege('access_verifier')"
              class="text-center w-full 2xl:w-1/5 lg:w-1/3 sm:w-1/2 shadow-lg transition duration-500 ease-in-out
                     transform hover:-translate-y-1 hover:scale-110 hover:shadow-2xl">
        <a routerLink="/verifier/list" class="block" (click)="setValue('verifier')">
            <div class="bg-verifier md:w-full bg-no-repeat bg-center h-64 transition duration-500 ease-in-out hover:opacity-30" style="background-size: 12rem"></div>
        </a>
        <div class="absolute inline-flex items-center justify-center w-12 h-10 text-md -right-1 font-bold
                    text-gray-900 bg-green-400 border-4 border-gray-900 rounded-full -top-4">
            {{ getUnseenBatches('verifier') }}
        </div>
        <mat-card-subtitle class="mb-5">
            {{ 'HOME.verifier' | translate }}
        </mat-card-subtitle>
    </mat-card>
</div>

// frontend/src/pages/home.tsx
/** This file is part of Open-Capture.

 Open-Capture is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.
 Open-Capture is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Open-Capture. If not, see <https://www.gnu.org/licenses/gpl-3.0.html>.

 @dev : Nathan CHEVAL <nathan.cheval@edissyum.com> */

import { useEffect, useState } from "react";

import { VerifierListPage } from "./verifier/list";
import { SplitterListPage } from "./splitter/list";

import { useUser } from "../services/hooks/useUser";
import { hasRequiredPermissions } from "../components/auth/auth";
import { t } from "i18next";

export function HomePage() {
    const modules: any = {
        verifier: VerifierListPage,
        splitter: SplitterListPage
    }
    const [module, setModule] = useState("");

    const {user, loadingUser} = useUser();

    const selectedModule = localStorage.getItem('selectedModule') || 'verifier';
    if (selectedModule && selectedModule !== module) {
        setModule(selectedModule);
    }

    const ModuleComponent = modules[selectedModule];

    useEffect(() => {
        const handler = () => {
            const module = localStorage.getItem('selectedModule');
            if (module) {
                setModule(module);
            }
        };

        window.addEventListener("updateModule", handler);
        return () => window.removeEventListener("updateModule", handler);
    }, []);

    if (loadingUser) return;

    if (selectedModule) {
        if (hasRequiredPermissions(user, selectedModule === 'verifier' ? ['access_verifier'] : ['access_splitter'])) {
            return (
                <ModuleComponent />
            );
        } else {
            return (
                <div className="flex flex-col items-center justify-center h-full gap-4">
                    <h1 className="text-2xl font-bold">{ t('GLOBAL.unauthorized') }</h1>
                    <p>{ t('GLOBAL.unauthorized_details') }</p>
                </div>
            );
        }
    }

    return (
        <ModuleComponent />
    );
}
