// src/frontend/app/login/login.component.ts
/** This file is part of Open-Capture for Invoices.

Open-Capture for Invoices is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Open-Capture is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Open-Capture for Invoices. If not, see <https://www.gnu.org/licenses/gpl-3.0.html>.

@dev : Nathan Cheval <nathan.cheval@outlook.fr> */

import {Component, OnInit} from '@angular/core';
import {Validators, FormBuilder} from '@angular/forms';
import {TranslateService} from "@ngx-translate/core";
import {API_URL} from "../env";
import {HttpClient} from "@angular/common/http";
import {NotificationService} from "../../services/notifications/notifications.service";
import {catchError, tap} from "rxjs/operators";
import {of} from "rxjs";
import {AuthService} from "../../services/auth.service";
import {Router} from "@angular/router";
import {ConfigService} from "../../services/config.service";
import {LocaleService} from "../../services/locale.service";
import {UserService} from "../../services/user.service";
import {HistoryService} from "../../services/history.service";

@Component({
    selector: 'app-login',
    templateUrl: './login.component.html',
    styleUrls: ['./login.component.scss']
})
export class LoginComponent implements OnInit {
    loginForm: any;

    constructor(
        private router: Router,
        private http: HttpClient,
        private formBuilder: FormBuilder,
        private authService: AuthService,
        private userService: UserService,
        private translate: TranslateService,
        private notify: NotificationService,
        private configService: ConfigService,
        private localeService: LocaleService,
        private historyService: HistoryService,
    ) {}

    ngOnInit(): void {
        this.loginForm = this.formBuilder.group({
            username: [null, Validators.required],
            password: [null, Validators.required]
        });
        if (this.localeService.currentLang === undefined) {
            this.localeService.getCurrentLocale();
        }
    }

    onSubmit() {
        const password = this.loginForm.get('password').value;
        const username = this.loginForm.get('username').value;
        if (password && username) {
            this.http.post(
                API_URL + '/ws/auth/login',
                {
                    'username': username,
                    'password': password,
                    'lang': this.localeService.currentLang
                },
                {
                    observe: 'response'
                },
            ).pipe(
                tap((data: any) => {
                    this.userService.setUser(data.body.user);
                    this.authService.setTokens(data.body.auth_token, btoa(JSON.stringify(this.userService.getUser())), data.body.days_before_exp);
                    this.authService.generateHeaders();
                    this.notify.success(this.translate.instant('AUTH.authenticated'));
                    this.configService.readConfig().then(() => {
                        this.historyService.addHistory('general', 'login', this.translate.instant('HISTORY-DESC.login'));
                        if (this.authService.getCachedUrl()) {
                            this.router.navigate([this.authService.getCachedUrl()]).then();
                            this.authService.cleanCachedUrl();
                        } else {
                            this.router.navigate(['/home']).then();
                        }
                    });
                }),
                catchError((err: any) => {
                    console.debug(err);
                    this.notify.handleErrors(err);
                    return of(false);
                })
            ).subscribe();
        }
    }

    getErrorMessage(field: any) {
        if(this.loginForm.get(field).hasError('required'))
            return this.translate.instant('AUTH.field_required');
        return this.translate.instant('ERROR.unknow_error');
    }
}

<div class="min-h-screen flex">
    <app-loader *ngIf="this.loading"></app-loader>
    <div class="w-full flex items-center justify-center text-center flex-col gap-y-8">
        <div class="w-11/12" *ngIf="this.loginImage">
            <img class="m-auto" [src]="this.loginImage" alt="Open-Capture logo">
        </div>
        <mat-card class="text-center m-12 w-full 2xl:w-1/4 sm:w-1/2">
            <mat-card-title class="mb-5">
                {{ 'GLOBAL.login' | translate }}
            </mat-card-title>
            <mat-card-subtitle class="mt-5 mb-5">
                {{ this.subtitle }}
            </mat-card-subtitle>
            <mat-card-content>
                <form [formGroup]="this.loginForm" (ngSubmit)="onSubmit()">
                    <mat-form-field class="block">
                        <mat-label>{{ 'USER.username' | translate }}</mat-label>
                        <input matInput id="username" formControlName="username" type="text" placeholder="{{ 'USER.username' | translate }}" required>
                        <mat-error *ngIf="this.loginForm.controls.username.invalid">{{ getErrorMessage('username') }}</mat-error>
                    </mat-form-field>
                    <mat-form-field class="block">
                        <mat-label>{{ 'USER.password' | translate }}</mat-label>
                        <input matInput id="password" name="password" autocomplete="off" formControlName="password"
                               [type]="this.showPassword ? 'text' : 'password'"
                               placeholder="{{ 'USER.password' | translate }}" required>
                        <mat-icon matSuffix (click)="this.showPassword = !this.showPassword"
                                  class="text-green-400 relative cursor-pointer -top-0.5 text-base">
                            <i class="fa fa-1x" [class.fa-eye-slash]="!this.showPassword" [class.fa-eye]="this.showPassword"></i>
                        </mat-icon>
                        <mat-error *ngIf="this.loginForm.controls.password.invalid">
                            {{ getErrorMessage('password') }}
                        </mat-error>
                        <mat-hint align="end" *ngIf="this.enableLoginMethodName === 'ldap'">
                            <span class="underline decoration-1" >
                                {{ this.enableLoginMethodName | uppercase }} {{ 'LOGIN-METHODS.enabled' | translate }}
                            </span>
                        </mat-hint>
                    </mat-form-field>
                    <button mat-button [disabled]="this.processLogin || this.isConnectionBtnDisabled"
                            class="min-w-56 p-6 border-solid border-green-400 border bg-green-400 text-white hover:bg-transparent hover:text-gray-900
                               transition duration-300" type="submit" id="login">
                        <span *ngIf="!this.processLogin && !this.isConnectionBtnDisabled">
                            {{ 'AUTH.login' | translate }}
                        </span>
                        <i *ngIf="this.processLogin || this.isConnectionBtnDisabled"
                           class="fa-solid text-2xl fa-circle-notch fa-spin text-gray-900"></i>
                    </button>
                </form>
            </mat-card-content>
            <span class="relative my-4 text-green-400 font-bold">
                <a href="https://kutt.it/GuideDutilisation" target="_blank">
                    {{ 'GLOBAL.utilisation_guide' | translate }}
                </a>
            </span>
            <div class="text-center relative top-8 text-gray-900" *ngIf="this.enableLoginMethodName === 'default'">
                <a routerLink="/forgotPassword">
                    {{ 'AUTH.forgot_password' | translate }}
                </a>
            </div>
        </mat-card>
    </div>
    <div>
        <div class="absolute bottom-0 right-0">
            <div class="flex flex-col gap-y-2">
                <div class="flex gap-x-2 mr-2 mb-2">
                    <span class="text-gray-900 text-sm">
                        Open-Capture version {{ environment.version }}
                        <span class="text-green-400">|</span>
                        Powered by
                        <a class="text-green-400" href="https://edissyum.com/" target="_blank">
                            Edissyum Consulting
                        </a>
                    </span>
                </div>
            </div>
        </div>
    </div>
</div>

// frontend/src/pages/login.tsx
/** This file is part of Open-Capture.

 Open-Capture is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 Open-Capture is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Open-Capture. If not, see <https://www.gnu.org/licenses/gpl-3.0.html>.

 @dev : Nathan CHEVAL <nathan.cheval@edissyum.com> */

import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { getI18n, useTranslation } from "react-i18next";

import { Button } from '../components/Button';
import { Input } from "../components/Input.tsx";
import { showToast } from "../components/ToastProvider.tsx";

import { useCustom } from "../services/custom/customContext.tsx";
import { axiosApiCall } from "../services/hooks/axiosApiCall.tsx";
import { useFormValues } from "../services/hooks/useFormValues.tsx";

export function Login() {
    const [loadingLogin, setLoadingLogin] = useState(false);

    const { t } = useTranslation();
    const { post } = axiosApiCall();
    const navigate = useNavigate();

    const custom = useCustom();

    const { handleSubmit, errors, handleChange } = useFormValues(async (values) => {
        try {
            setLoadingLogin(true);
            const data = {
                lang: getI18n().language,
                username: values.username.value,
                password: values.password.value
            };

            const response = await post("/auth/login", data);
            if (response) {
                showToast(t('AUTH.authenticated'));

                if (response.admin_password_alert) {
                    showToast(t('ERROR.admin_password_alert'), "warning");
                }

                sessionStorage.setItem("accessToken", response.auth_token);
                sessionStorage.setItem("refreshToken", response.refresh_token);
                sessionStorage.setItem("user", JSON.stringify(response.user));

                const onboardingCompleted = localStorage.getItem('onboardingCompleted');
                if (!onboardingCompleted) {
                    navigate('/onboarding', { replace: true });
                    setLoadingLogin(false);
                    return;
                }
                navigate('/home', { replace: true });
            }
            setLoadingLogin(false);
        } catch (err) {
            setLoadingLogin(false);
            return null;
        }
    }, t);

    return (
        <div className="flex min-h-full flex-col justify-center px-6 py-12 lg:px-8">
            <div className="sm:mx-auto sm:w-full sm:max-w-sm">
                <img src={"/src/assets/imgs/login_image.svg"} alt="Open-Capture" className="mx-auto" />
                <h2 className="mt-10 text-center text-2xl/9 tracking-tight text-(--text-primary)">
                    { t("GLOBAL.login") }
                </h2>
            </div>

            <div className="mt-10 sm:mx-auto sm:w-full sm:max-w-sm">
                <form onSubmit={handleSubmit} className="space-y-6" noValidate>
                    <div className="mt-2">
                        <Input id="username" type="text" name="username" required error={errors.username} onChange={handleChange} label={ t('USER.username') }/>
                    </div>
                    <div>
                        <Input id="password" type="password" name="password" required error={errors.password} onChange={handleChange} label={ t('USER.password') }/>
                    </div>

                    <div className="text-center">
                        <Button disabled={!custom} loading={loadingLogin} type="submit" size='md' className="w-full">
                            { t('AUTH.login') }
                        </Button>
                        {!custom && <p className="mt-2 text-sm text-(--text-secondary)">{ t('ERROR.custom_not_provided') }</p>}
                    </div>
                </form>
            </div>
        </div>
    );
}
