// src/frontend/app/profile/profile.component.ts
/** This file is part of Open-Capture.

Open-Capture is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Open-Capture is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Open-Capture. If not, see <https://www.gnu.org/licenses/gpl-3.0.html>.

@dev : Nathan Cheval <nathan.cheval@outlook.fr>
@dev : Oussama Brich <oussama.brich@edissyum.com>  */

import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from "@angular/router";
import { AuthService } from "../../services/auth.service";
import { UserService } from "../../services/user.service";
import { FormControl } from "@angular/forms";
import { TranslateService } from "@ngx-translate/core";
import { environment } from  "../env";
import { catchError, finalize, tap } from "rxjs/operators";
import { of } from "rxjs";
import { HttpClient, HttpHeaders } from "@angular/common/http";
import { NotificationService } from "../../services/notifications/notifications.service";
import { PrivilegesService } from "../../services/privileges.service";
import { PasswordVerificationService } from "../../services/password-verification.service";

@Component({
    selector: 'app-user-profile',
    templateUrl: './profile.component.html',
    styleUrls: ['./profile.component.scss']
})
export class UserProfileComponent implements OnInit {
    headers                     : HttpHeaders   = this.authService.headers;
    loading                     : boolean       = true;
    userId                      : any;
    profile                     : any;
    roles                       : any[]         = [];
    profileForm                 : any[]         = [
        {
            id: 'firstname',
            label: this.translate.instant('USER.firstname'),
            type: 'text',
            control: new FormControl(),
            required: true
        },
        {
            id: 'lastname',
            label: this.translate.instant('USER.lastname'),
            type: 'text',
            control: new FormControl(),
            required: true
        },
        {
            id: 'email',
            label: this.translate.instant('USER.email'),
            type: 'text',
            control: new FormControl(),
            required: false
        },
        {
            id: 'old_password',
            label: this.translate.instant('USER.old_password'),
            type: 'password',
            control: new FormControl(),
            required: false
        },
        {
            id: 'new_password',
            label: this.translate.instant('USER.new_password'),
            type: 'password',
            control: new FormControl(),
            required: false
        },
        {
            id: 'role',
            label: this.translate.instant('HEADER.role'),
            type: 'select',
            values: [],
            control: new FormControl(),
            required: false
        }
    ];
    disablePasswordModification : boolean       = false;

    constructor(
        private http: HttpClient,
        private router: Router,
        private route: ActivatedRoute,
        public userService: UserService,
        private authService: AuthService,
        private translate: TranslateService,
        private notify: NotificationService,
        private privilegeService: PrivilegesService,
        private passwordVerification: PasswordVerificationService
    ) { }

    ngOnInit() {
        if (!this.authService.headersExists) {
            this.authService.generateHeaders();
        }
        this.userService.user   = this.userService.getUserFromLocal();

        this.http.get(environment['url'] + '/ws/auth/retrieveLoginMethodName').pipe(
            tap((data: any) => {
                data.login_methods.forEach((method: any) => {
                    if (method.enabled) {
                        if (method.method_name !== 'default') {
                            this.disablePasswordModification = true;
                        }
                    }
                });
            }),
            catchError ((err: any) => {
                console.debug(err);
                this.notify.handleErrors(err);
                return of (false);
            })
        ).subscribe();

        this.userId = parseInt(this.route.snapshot.params['id']);
        const loggedUserId = this.userService.user.id;

        if (this.userId !== parseInt(loggedUserId)) {
            if (!this.privilegeService.hasPrivilege('update_user')) {
                this.translate.get('ERROR.unauthorized').subscribe((translated: string) => {
                    this.notify.error(translated);
                    this.router.navigateByUrl('/home').then();
                });
            }
        }

        this.http.get(environment['url'] + '/ws/roles/list/user/' + this.userService.user.id + '?full',
            {headers: this.authService.headers}).pipe(
                tap((data: any) => {
                data.roles.forEach((element: any) => {
                    if (element.editable) {
                        this.roles.push(element);
                    } else {
                        if ((this.userService.getUser().privileges === '*')) {
                            this.roles.push(element);
                        }
                    }
                });
            }),
            catchError((err: any) => {
                console.debug(err);
                this.notify.handleErrors(err);
                return of(false);
            })
        ).subscribe();

        this.http.get(environment['url'] + '/ws/users/getById/' + this.userId, {headers: this.authService.headers}).pipe(
            tap((data: any) => {
                this.profile = data;
                for (const field in this.profile) {
                    if (this.profile.hasOwnProperty(field)) {
                        this.profileForm.forEach(element => {
                            if (element.id === field) {
                                element.control.setValue(this.profile[field]);
                                if (element.id === 'role') {
                                    element.values = this.roles;
                                }
                            }
                        });
                    }
                }
            }),
            finalize(() => this.loading = false),
            catchError((err: any) => {
                console.debug(err);
                this.notify.handleErrors(err);
                return of(false);
            })
        ).subscribe();

        this.profileForm.forEach((element: any) => {
            if (element.id === 'new_password') {
                element.control.valueChanges.subscribe((value: any) => {
                    if (value) {
                        this.passwordVerification.checkPasswordValidityUnique(this.profileForm);
                    }
                    this.profileForm.filter((element: any) => element.id === 'old_password')[0].required = !!value;
                });
            }
        });
    }

    isValidForm() {
        let state = true;
        this.profileForm.forEach(element => {
            if (element.control.status !== 'DISABLED' && element.control.status !== 'VALID') {
                state = false;
            }
            element.control.markAsTouched();
        });
        return state;
    }

    onSubmit() {
        if (this.isValidForm()) {
            this.loading = true;
            const user : any = {};
            this.profileForm.forEach(element => {
                user[element.id] = element.control.value;
            });

            this.http.put(
                environment['url'] + '/ws/users/update/' + this.userId, {'args': user},
                {headers: this.authService.headers},
            ).pipe(
                tap((data: any) => {
                    this.notify.success(this.translate.instant('USER.profile_updated'));
                    if (this.userId === this.userService.user.id) {
                        this.userService.setUser(data.user);
                    }
                }),
                finalize(() => this.loading = false),
                catchError((err: any) => {
                    console.debug(err);
                    this.notify.handleErrors(err);
                    return of(false);
                })
            ).subscribe();
        }
    }

    getErrorMessage(field: any) {
        let error: any;

        this.profileForm.forEach(element => {
            if (element.id === field) {
                if (element.control.errors && element.control.errors.message) {
                    error = element.control.errors.message;
                }
                if (element.required) {
                    error = this.translate.instant('AUTH.field_required');
                }
            }
        });
        return error;
    }
}

@if (!loading) {
    <div class="flex justify-center items-center" style="height: 85vh">
        <mat-card class="text-center w-full lg:w-1/4">
            <mat-card-title class="mb-10">
                @if (this.userId === this.userService.user.id) {
                    <span>{{ 'USER.modify_my_profile' | translate }}</span>
                } @else {
                    <span>{{ 'USER.modify_profile_of' | translate }} {{ this.profile['username'] }}</span>
                }
            </mat-card-title>
            <mat-card-content>
                <form (ngSubmit)="onSubmit()">
                    @for (field of profileForm; track field.id) {
                        @if (field.type === 'select') {
                            <mat-form-field class="block">
                                <mat-label>{{ field.label | translate }}</mat-label>
                                <mat-select [disabled]="this.userService.getUserFromLocal()['username'] === 'admin' || this.userService.getUserFromLocal()['privileges'] !== '*'" [(value)]="field.control.value">
                                    @for (option of field.values; track option['id']) {
                                        <mat-option [value]="option['id']">
                                            {{ option['label'] }}
                                        </mat-option>
                                    }
                                </mat-select>
                            </mat-form-field>
                        } @else {
                            <mat-form-field class="block m-2" [class.pointer-events-none]="field.type === 'password' && this.disablePasswordModification">
                                <mat-label [class.text-gray-400]="field.type === 'password' && this.disablePasswordModification">
                                    {{ field.label | translate }}
                                </mat-label>
                                <input [readonly]="field.type === 'password' && this.disablePasswordModification" matInput
                                       [formControl]="field['control']" [type]="field.type" [required]="field['required']"
                                       [email]="field.type === 'email'" [placeholder]="field.label | translate">
                                @if (field.control.invalid) {
                                    <mat-error class="text-red-400" [innerHTML]="getErrorMessage(field.id)"></mat-error>
                                }
                                @if (field.id === 'old_password') {
                                    <mat-icon matSuffix (click)="field.type === 'password' ? field.type = 'text' : field.type = 'password'"
                                              class="text-green-400 relative cursor-pointer -top-0.5 text-base">
                                        <i class="fa fa-1x" [class.fa-eye-slash]="field.type === 'password'" [class.fa-eye]="field.type !== 'password'"></i>
                                    </mat-icon>
                                } @else if (field.id === 'new_password') {
                                    <mat-icon matSuffix (click)="field.type === 'password' ? field.type = 'text' : field.type = 'password'"
                                              class="text-green-400 relative cursor-pointer -top-0.5 text-base">
                                        <i class="fa fa-1x" [class.fa-eye-slash]="field.type === 'password'" [class.fa-eye]="field.type !== 'password'"></i>
                                    </mat-icon>
                                }
                            </mat-form-field>
                        }
                    }
                    <div class="button col-span-3">
                        <button class="valid_button" type="submit" mat-button>
                            {{ 'USER.modify' | translate }}
                        </button>
                    </div>
                </form>
            </mat-card-content>
        </mat-card>
    </div>
}

// frontend/src/pages/profile.tsx
/** This file is part of Open-Capture.

 Open-Capture is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.
 Open-Capture is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Open-Capture. If not, see <https://www.gnu.org/licenses/gpl-3.0.html>.

 @dev : Nathan CHEVAL <nathan.cheval@edissyum.com> */

import { z } from "zod";
import { t } from "i18next";
import { useForm } from "react-hook-form";
import { useEffect, useState } from "react";
import { zodResolver } from "@hookform/resolvers/zod";

import { USER_KEY, useUser } from "../services/hooks/useUser";
import { AxiosApiCall } from "../services/hooks/AxiosApiCall";
import { usePasswordRules } from "../services/hooks/usePasswordRules";

import { Button } from "../components/Button";
import { showToast } from "../components/ToastProvider";
import { DynamicForm } from "../components/form/DynamicForm";

export default function ProfilePage() {
    const { get, put } = AxiosApiCall();
    const { user, loadingUser } = useUser();
    const { verifyPassword } = usePasswordRules();
    const [loading, setLoading] = useState(true);
    const [loadingSubmit, setLoadingSubmit] = useState(false);

    const [disablePassword, setDisablePassword] = useState(false);

    // Fetch login method
    useEffect(() => {
        if (!user) return;

        const fetchLoginMethod = async () => {
            try {
                const res = await get('/auth/getEnabledLoginMethod');
                if (res.login_method_name) {
                    setDisablePassword(res.login_method_name[0].method_name !== 'default');
                }
            } catch (error) {
                console.error('Error fetching login method:', error);
            }
        };

        fetchLoginMethod().then();
    }, [user]);

    const schemaDetails = z.object({
        lastname: z.string().min(1).describe(JSON.stringify({
            component: "input",
            required: true,
            type: "text",
            label: t("USERS.lastname")
        })),
        firstname: z.string().min(1).describe(JSON.stringify({
            component: "input",
            required: true,
            type: "text",
            label: t("USERS.firstname")
        })),
        email: z.string().optional().describe(JSON.stringify({
            component: "input",
            required: false,
            type: "text",
            label: t("USERS.email")
        })),
        password: z.string().optional().describe(JSON.stringify({
            component: "input",
            type: "password",
            show: !disablePassword,
            label: t("USERS.password")
        })),
        password_check: z.string().optional().describe(JSON.stringify({
            component: "input",
            type: "password",
            show: !disablePassword,
            label: t("USERS.password_check")
        })),
    });

    const { control, watch, setValue, handleSubmit, clearErrors, setError, formState: { errors } } = useForm({
        resolver: zodResolver(schemaDetails),
        mode: "onChange",
        defaultValues: {
            lastname: "",
            firstname: "",
            email: "",
            password: "",
            password_check: ""
        },
    });

    const password: any = watch("password");
    const passwordCheck: any = watch("password_check");

    // Validate password and password check fields
    useEffect(() => {
        if (!password) {
            clearErrors("password");
            clearErrors("password_check");
            return;
        }

        const errorMessage = verifyPassword(password);
        if (errorMessage) {
            setTimeout(() => {
                setError("password", { message: errorMessage });
            }, 0);
        } else {
            clearErrors("password");
        }

        if (password !== passwordCheck) {
            setError("password_check", {
                message: t("USERS.password_mismatch")
            });

            setError("password", {
                message: t("USERS.password_mismatch")
            });
        } else {
            clearErrors("password");
            clearErrors("password_check");
        }
    }, [password, passwordCheck]);

    // Retrieve user profile information and display it
    useEffect(() => {
        if (!user) return;

        const fetchUserProfile = async () => {
            try {
                const res = await get(`/users/profile/${ user.id }/${ user.id }`);
                setValue('lastname', res.lastname || "");
                setValue('firstname', res.firstname || "");
                setValue('email', res.email || "");
            } catch (error) {
                console.error('Error fetching user profile:', error);
            } finally {
                setLoading(false);
            }
        }

        fetchUserProfile().then();
    }, [loadingUser, user]);

    const handleUpdateProfile = async (data: any) => {
        if (errors && Object.keys(errors).length > 0) return;

        setLoadingSubmit(true);
        if (disablePassword || (!data.password && !data.password_check)) {
            delete data.password;
            delete data.password_check;
        }

        try {
            await put(`/users/update/${ user.id }`, data);
            showToast(t('PROFILE.update_success'));
            sessionStorage.setItem(USER_KEY, JSON.stringify({ ...user, ...data }));
        } catch (error) {
            console.error('Error updating profile:', error);
            showToast(t('PROFILE.update_error'), 'error');
        } finally {
            setLoadingSubmit(false);
        }
    }

    if (!user) return;

    return (
        <div className="p-6 flex flex-col gap-6">
            <h3 className="text-xl font-bold">{ t('PROFILE.details') }</h3>
            <div className='w-1/3'>
                <DynamicForm schema={ schemaDetails } errors={ errors } control={ control }/>
            </div>

            <Button onClick={ handleSubmit(handleUpdateProfile) }
                    disabled={ loading || loadingSubmit || Object.keys(errors).length > 0 }>
                { loadingSubmit ? t('GLOBAL.updating') : t('PROFILE.update_profile') }
            </Button>
        </div>
    );
}
