// src/frontend/app/reset-password/reset-password.component.ts
/** This file is part of Open-Capture.

 Open-Capture is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 Open-Capture is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Open-Capture. If not, see <https://www.gnu.org/licenses/gpl-3.0.html>.

 @dev : Nathan Cheval <nathan.cheval@outlook.fr> */

import { Component, OnInit } from '@angular/core';
import { DomSanitizer, SafeUrl } from "@angular/platform-browser";
import { FormControl } from "@angular/forms";
import { ActivatedRoute } from "@angular/router";
import { HttpClient } from "@angular/common/http";
import { AuthService } from "../../services/auth.service";
import { TranslateService } from "@ngx-translate/core";
import { NotificationService } from "../../services/notifications/notifications.service";
import { LocaleService } from "../../services/locale.service";
import { SessionStorageService } from "../../services/session-storage.service";
import { environment } from "../env";
import { catchError, finalize, tap } from "rxjs/operators";
import { of } from "rxjs";
import { PasswordVerificationService } from "../../services/password-verification.service";

@Component({
    selector: 'app-reset-password',
    templateUrl: './reset-password.component.html',
    styleUrls: ['./reset-password.component.scss']
})
export class ResetPasswordComponent implements OnInit {
    loading                 : boolean = true;
    showPassword            : boolean = false;
    image                   : SafeUrl = '';
    resetToken              : string  = '';
    passwordForm            : any[]   = [
        {
            id: 'password',
            label: this.translate.instant('USER.password'),
            type: 'password',
            control: new FormControl()
        },
        {
            id: 'password_check',
            label: this.translate.instant('USER.password_check'),
            type: 'password',
            control: new FormControl()
        }
    ];

    constructor(
        private http: HttpClient,
        private route: ActivatedRoute,
        private sanitizer: DomSanitizer,
        private authService: AuthService,
        private translate: TranslateService,
        private notify: NotificationService,
        private localeService: LocaleService,
        private sessionStorageService: SessionStorageService,
        public passwordVerification: PasswordVerificationService
    ) {}

    ngOnInit(): void {
        if (this.localeService.currentLang === undefined) {
            this.localeService.getCurrentLocale();
        }
        this.resetToken = this.route.snapshot.queryParams['reset_token'];
        if (!this.resetToken) {
            this.translate.get('AUTH.token_not_provided').subscribe((translated: string) => {
                this.notify.error(this.translate.instant(translated));
                this.authService.logout();
            });
        }
        const b64Content = this.sessionStorageService.get('loginImageB64');
        if (!b64Content) {
            this.http.get(environment['url'] + '/ws/config/getLoginImage').pipe(
                tap((data: any) => {
                    this.sessionStorageService.save('loginImageB64', data);
                    this.image = this.sanitizer.bypassSecurityTrustUrl('data:image/png;base64, ' + data);
                }),
                finalize(() => { this.loading = false; }),
                catchError((err: any) => {
                    console.debug(err);
                    this.notify.handleErrors(err);
                    return of(false);
                })
            ).subscribe();
        } else {
            this.image = this.sanitizer.bypassSecurityTrustUrl('data:image/png;base64, ' + b64Content);
            this.loading = false;
        }

        this.passwordForm.forEach((element: any) => {
            element.control.valueChanges.subscribe((value: any) => {
                if (value) {
                    this.passwordVerification.checkPasswordValidity(this.passwordForm);
                }
            });
        });
    }

    onSubmit() {
        const passwordConfirm = this.passwordForm.filter((element: any) => element.id === 'password_check')[0].control.value;
        this.http.put(environment['url'] + '/ws/users/resetPassword', {resetToken: this.resetToken, newPassword: passwordConfirm}).pipe(
            tap(() => {
                this.notify.success(this.translate.instant('USER.password_reset_success'));
                this.authService.logout();
            }),
            catchError((err: any) => {
                console.debug(err);
                this.notify.handleErrors(err);
                return of(false);
            })
        ).subscribe();
    }

    getErrorMessage(field: any) {
        let error: any;
        this.passwordForm.forEach(element => {
            if (element.id === field) {
                if (element.control.errors && element.control.errors.message) {
                    error = element.control.errors.message;
                }
                if (element.required && !(element.value || element.control.value)) {
                    error = this.translate.instant('AUTH.field_required');
                }
            }
        });
        return error;
    }
}

<div class="relative top-16 2xl:top-32 flex justify-center h-20" *ngIf="this.image">
    <img [src]="this.image" alt="Open-Capture logo">
</div>
<div class="flex justify-center items-center" style="height: 85vh">
    <app-loader *ngIf="this.loading"></app-loader>
    <mat-card class="text-center w-full 2xl:w-1/4 sm:w-1/2">
        <mat-card-title class="my-4">
            {{ 'GLOBAL.reset-password' | translate }}
        </mat-card-title>
        <app-hint class="mx-2" [specificClass]="'w-full'" [message]="'AUTH.password_min_length' | translate : {min: passwordRules.minLength}"></app-hint>
        <app-hint *ngIf="passwordRules.specialCharMandatory" class="mx-2 -mt-5" [specificClass]="'w-full'" [message]="'AUTH.password_special_char_mandatory' | translate"></app-hint>
        <app-hint *ngIf="passwordRules.uppercaseMandatory" class="mx-2 -mt-5" [specificClass]="'w-full'" [message]="'AUTH.password_uppercase_mandatory' | translate"></app-hint>
        <app-hint *ngIf="passwordRules.numberMandatory" class="mx-2 -mt-5" [specificClass]="'w-full'" [message]="'AUTH.password_number_mandatory' | translate"></app-hint>
        <mat-card-content>
            <form (ngSubmit)="onSubmit()">
                <mat-form-field class="block mb-4">
                    <mat-label>{{ 'USER.password' | translate }}</mat-label>
                    <input matInput [formControl]="this.passwordControl" (keyup)="checkPasswordValidity()"
                           [type]="this.showPassword ? 'text' : 'password'" placeholder="{{ 'USER.password' | translate }}" required>
                    <mat-icon matSuffix (click)="this.showPassword = !this.showPassword"
                              class="text-green-400 relative cursor-pointer -top-0.5 text-base">
                        <i class="fa fa-1x" [class.fa-eye-slash]="!this.showPassword" [class.fa-eye]="this.showPassword"></i>
                    </mat-icon>
                    <mat-hint class="text-red-400" *ngIf="this.errorMessage !== ''" [innerHTML]="this.errorMessage"></mat-hint>
                </mat-form-field>
                <mat-form-field class="block mb-2">
                    <mat-label>{{ 'USER.password_check' | translate }}</mat-label>
                    <input matInput [formControl]="this.passwordConfirmControl" [type]="this.showPasswordConfirm ? 'text' : 'password'" placeholder="{{ 'USER.password_check' | translate }}" required>
                    <mat-icon matSuffix (click)="this.showPasswordConfirm = !this.showPasswordConfirm"
                              class="text-green-400 relative cursor-pointer -top-0.5 text-base">
                        <i class="fa fa-1x" [class.fa-eye-slash]="!this.showPasswordConfirm" [class.fa-eye]="this.showPasswordConfirm"></i>
                    </mat-icon>
                    <mat-hint class="text-red-400" *ngIf="this.passwordConfirmControl.value && this.passwordConfirmControl.value !== this.passwordControl.value">
                        {{'USER.password_mismatch' | translate}}
                    </mat-hint>
                </mat-form-field>
                <div [class.cursor-not-allowed]="this.errorMessage !== '' || this.passwordControl.value !== this.passwordConfirmControl.value || !this.passwordControl.value || !this.passwordConfirmControl.value">
                    <button mat-button [disabled]="this.errorMessage !== '' || this.passwordControl.value !== this.passwordConfirmControl.value || !this.passwordControl.value || !this.passwordConfirmControl.value"
                            [class.bg-gray-400]="this.errorMessage !== '' || this.passwordControl.value !== this.passwordConfirmControl.value ||!this.passwordControl.value || !this.passwordConfirmControl.value"
                            [class.bg-green-400]="this.errorMessage === '' && this.passwordControl.value === this.passwordConfirmControl.value && this.passwordControl.value && this.passwordConfirmControl.value"
                            class="w-1/2 p-6 border-solid bg-green-400 border-green-400 border text-white
                                        hover:bg-transparent hover:text-gray-900 transition duration-300" type="submit">
                        {{ 'AUTH.modify_password' | translate }}
                    </button>
                </div>
            </form>
        </mat-card-content>
        <div class="text-center relative top-8 text-gray-900">
            <a routerLink="/login">
                {{ 'AUTH.back_to_login' | translate }}
            </a>
        </div>
    </mat-card>
</div>

// frontend/src/pages/reset-password.tsx
/** This file is part of Open-Capture.

 Open-Capture is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 Open-Capture is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Open-Capture. If not, see <https://www.gnu.org/licenses/gpl-3.0.html>.

 @dev : Nathan CHEVAL <nathan.cheval@edissyum.com> */

import { z } from "zod";
import { t } from "i18next";
import { useForm } from "react-hook-form";
import { useEffect, useState } from "react";
import { zodResolver } from "@hookform/resolvers/zod";
import { useNavigate, useSearchParams } from "react-router-dom";

import Hint from "../components/Hint";
import Input from "../components/Input";
import { Button } from "../components/Button";
import { handleLogout } from "../components/Sidebar";
import { Loader } from "../components/loader/Loader";
import { LoginImage } from "../components/LoginImage";
import { showToast } from "../components/ToastProvider";
import { DynamicForm } from "../components/form/DynamicForm";

import { AxiosApiCall } from "../services/hooks/AxiosApiCall";
import { usePasswordRules } from "../services/hooks/usePasswordRules";

export function ResetPassword() {
    const [searchParams] = useSearchParams();
    const { get, post, put } = AxiosApiCall();
    const navigate = useNavigate();
    const { verifyPassword } = usePasswordRules();

    const [loading, setLoading] = useState(true);
    const [sending, setSending] = useState(false);
    const [resetToken, setResetToken] = useState('');
    const [smtpStatus, setSmtpStatus] = useState(true);

    document.title = t('AUTH.reset-password') + " - Open-Capture";

    useEffect(() => {
        const token = searchParams.get("reset_token");
        if (token) {
            setResetToken(token);
        }
    }, []);

    const [email, setEmail] = useState('');
    const [emailError, setEmailError] = useState('');

    const passwordSchema = z.object({
        password: z.string().describe(JSON.stringify({
            component: "input",
            type: "password",
            required: true,
            label: t("USERS.password")
        })),
        password_confirm: z.string().describe(JSON.stringify({
            component: "input",
            type: "password",
            required: true,
            label: t("USERS.password_confirm")
        })),
    }).refine((data) => data.password === data.password_confirm, {
        message: t('USERS.passwords_do_not_match'),
    });

    const { control, watch, setError, clearErrors, formState: { errors } } = useForm({
        resolver: zodResolver(passwordSchema),
        defaultValues: {},
        mode: "onChange"
    });
    const password = watch('password');
    const passwordConfirm = watch('password_confirm');

    // Check password validity
    useEffect(() => {
        const errorMessage = verifyPassword(password);

        if (errorMessage) {
            setTimeout(() => {
                setError("password", { message: errorMessage });
            }, 0);
        } else {
            clearErrors("password");
        }

        if (password && passwordConfirm) {
            if (password !== passwordConfirm) {
                setError('password', { message: t('USERS.passwords_do_not_match') });
                setError('password_confirm', { message: t('USERS.passwords_do_not_match') });
            } else {
                clearErrors('password');
                clearErrors('password_confirm');
            }
        }
    }, [password, passwordConfirm]);

    // Check if smtp server is up
    useEffect(() => {
        const checkSmtpServer = async () => {
            try {
                const response = await get('/smtp/isServerUp')
                setSmtpStatus(response.status);
                setLoading(false);
            } catch (err) {
                setLoading(false);
                console.debug(err);
            }
        };

        checkSmtpServer().then();
    }, []);

    const handleNavigateToLogin = () => {
        navigate('/login');
    };

    const checkEmail = (e: any) => {
        setEmail(e.target.value);
        const emailPattern = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
        if (!emailPattern.test(e.target.value)) {
            setEmailError(t('USERS.invalid_email'));
        } else {
            setEmailError('');
        }
    }

    const handleReset = async (e: any) => {
        e.preventDefault();

        if (Object.keys(errors).length > 0 || !password || !passwordConfirm) {
            return;
        }

        setSending(true);

        try {
            await put('/users/resetPassword', { resetToken: resetToken, newPassword: passwordConfirm });
            showToast(t('AUTH.password_reset_success'), 'success');
            handleLogout(navigate).then();
        } catch (err) {
            setSending(false);
            console.debug('Error while resetting password', err);
        }
    }

    const handleSendEmail = async (e: any) => {
        e.preventDefault();

        if (emailError || !email) {
            return;
        }

        setSending(true);

        try {
            const response = await post('/users/getByMail', { 'email': email })
            if (response && response.id) {
                const currentUrl = window.location.href.replace('/reset-password', '');
                await post('/users/sendEmailForgotPassword', { 'userId': response.id, 'currentUrl': currentUrl });
                showToast(t('AUTH.forgot_password_email_sent'), 'success');
                setSending(false);
            }
        } catch (err) {
            setSending(false);
            console.debug('Error while sending reset password email', err);
        }
    };

    if (loading) {
        return (
            <div className='h-screen'>
                <Loader/>
            </div>
        );
    }

    return (
        <div className="flex h-screen flex-col items-center justify-center py-6 bg-(--bg-secondary)">
            <div className="bg-(--bg-primary) h-auto flex justify-center w-130 p-8 rounded-xl">
                <div className='flex flex-1 flex-col'>
                    <div className="sm:mx-auto w-3/5 mb-10">
                        <LoginImage className="mx-auto"></LoginImage>
                    </div>
                    <div className='flex flex-col align-center h-full justify-center'>
                        <div className='font-bold mb-4'>
                            <span className='text-2xl'>{ t('AUTH.reset-password') }</span>
                        </div>
                        { !smtpStatus && (
                            <Hint variant="error">
                                { t('AUTH.smtp-server-down') }
                            </Hint>
                        ) }

                        { resetToken ? (
                            <form onSubmit={ handleReset } className="flex flex-col gap-4">
                                <DynamicForm schema={ passwordSchema } errors={ errors } control={ control }/>
                                <Button loading={ sending } type="submit" className='w-full'
                                        disabled={ Object.keys(errors).length > 0 || !password || !passwordConfirm }>
                                    { t('AUTH.reset') }
                                </Button>
                            </form>
                        ) : (
                            <form onSubmit={ handleSendEmail } className="flex flex-col gap-4">
                                <Input id="email" type="text" name="email" required disabled={ !smtpStatus }
                                       onChange={ checkEmail } error={ emailError }
                                       label={ t('USERS.email') }/>

                                <Button loading={ sending } type="submit" className='w-full'
                                        disabled={ !smtpStatus || !!emailError || !email }>
                                    { t('AUTH.send_email') }
                                </Button>
                            </form>
                        ) }
                    </div>
                </div>
            </div>
            <p className='text-(--text-secondary) text-xs text-center mt-2'>
                { t('AUTH.know_password') }&nbsp;
                <span onClick={ handleNavigateToLogin }
                      className="cursor-pointer text-(--color-primary)">{ t('AUTH.login_here') } </span>
            </p>
        </div>
    )
}
