// frontend/src/pages/settings/index.tsx
/** This file is part of Open-Capture.

 Open-Capture is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.
 Open-Capture is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Open-Capture. If not, see <https://www.gnu.org/licenses/gpl-3.0.html>.

 @dev : Nathan CHEVAL <nathan.cheval@edissyum.com> */

import { t } from "i18next";
import { Check, Search, SlidersHorizontal } from "lucide-react";

import { SettingsCard } from "../../components/settings/SettingsCard";

export function SettingsIndex() {
    const options = [
        {
            name: t('SETTINGS.general'),
            description: t('SETTINGS.general_description'),
            icon: <SlidersHorizontal />,
            href: '/settings/general'
        },
        {
            name: t('SETTINGS.verifier'),
            description: t('SETTINGS.verifier_description'),
            icon: <Check />,
            href: '/settings/verifier'
        },
        {
            name: t('SETTINGS.splitter'),
            description: t('SETTINGS.splitter_description'),
            icon: <Search />,
            href: '/settings/splitter'
        },
    ];

    return (
        <div className="p-4">
            <h1 className="text-2xl font-bold mb-4">
                { t('SETTINGS.title') }
            </h1>
            <p className="text-(--text-secondary)">
                { t('SETTINGS.subtitle') }
            </p>
            <div className='flex flex-row gap-4 mt-6'>
                {
                    options.map((option) => (
                        <SettingsCard icon={option['icon']} title={option['name']} description={option['description']} to={option['href']}></SettingsCard>
                    ))
                }
            </div>
        </div>
    );
}

// src/frontend/app/settings/settings.component.ts
/** This file is part of Open-Capture for Invoices.

 Open-Capture for Invoices is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 Open-Capture is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Open-Capture for Invoices. If not, see <https://www.gnu.org/licenses/gpl-3.0.html>.

 @dev : Nathan Cheval <nathan.cheval@outlook.fr> */

import { Component, OnInit } from '@angular/core';
import { Router } from "@angular/router";
import { UserService } from "../../services/user.service";
import { SettingsService } from "../../services/settings.service";
import { PrivilegesService } from "../../services/privileges.service";

@Component({
    selector: 'app-panel',
    templateUrl: "settings.component.html"
})

export class SettingsComponent implements OnInit {
    selectedSetting         : string    = this.serviceSettings.getSelectedSetting();
    selectedParentSetting   : string    = this.serviceSettings.getSelectedParentSetting();
    settings                : any       = this.serviceSettings.getSettings();

    constructor(
        public router: Router,
        public userService: UserService,
        public serviceSettings: SettingsService,
        public privilegesService: PrivilegesService
    ) {}

    ngOnInit(): void {
        this.serviceSettings.init();
        this.selectedSetting = this.serviceSettings.getSelectedSetting();
        this.selectedParentSetting = this.serviceSettings.getSelectedParentSetting();
        this.settings = this.serviceSettings.getSettings();
        let settingsFound = false;
        this.settings[this.selectedParentSetting].forEach((element: any) => {
            if (element['id'] === this.selectedSetting) {
                settingsFound = true;
                const routeToGo = element.route;
                if (routeToGo && this.privilegesService.hasPrivilege(element.privilege))
                    this.router.navigateByUrl(routeToGo).then();
            }
        });

        if (!settingsFound)
            this.router.navigateByUrl('/settings/general/configurations').then();
    }
}

<mat-sidenav-container class="absolute left-0 right-0 bottom-0" style="top: 4.1rem">
    <mat-sidenav #sidenav mode="side" opened class="w-1/6 flex flex-col h-full border-r border-green-400" style="top:0.1rem">
        <h3 class="bg-green-400 bg-opacity-60 text-center text-gray-900 m-0 pb-4" style="padding-top: 0.9rem">{{ "SETTINGS.administration" | translate }}</h3>
        <mat-divider class="border-green-400"></mat-divider>
        <mat-nav-list class="pt-0">
            <mat-expansion-panel *ngFor="let parent of this.serviceSettings.getSettingsParent()"
                                 [expanded]="this.serviceSettings.getSelectedParentSetting() == parent['id']">
                <mat-expansion-panel-header>
                    <mat-panel-title>
                        {{ parent['label'] | translate }}
                    </mat-panel-title>
                </mat-expansion-panel-header>
                <div class="w-full border-t-2 border-gray-600">
                    <div *ngFor="let setting of this.serviceSettings.getSettings()[parent['id']];"
                         [class.border-b]="this.privilegesService.hasPrivilege(setting['privilege']) || setting['privilege'] == '*'"
                         [class.border-gray-400]="this.privilegesService.hasPrivilege(setting['privilege']) || setting['privilege'] == '*'">
                        <div *ngIf="this.serviceSettings.getSettingsAction(setting['id']) else noActions">
                            <mat-expansion-panel *ngIf="this.privilegesService.hasPrivilege(setting['privilege']) || setting['privilege'] == '*'"
                                                 [expanded]="this.serviceSettings.getSelectedSetting() == setting['id']">
                                <mat-expansion-panel-header class="font-normal w-full h-20">
                                    <mat-panel-title class="font-normal justify-center items-center text-center">
                                        <i [class.text-green-400]="this.router.url == setting['route']"
                                           class="absolute text-lg left-4 w-10 h-10 rounded-full flex items-center justify-center {{setting['icon']}}">
                                        </i>
                                        <button mat-button [class.text-green-400]="this.router.url == setting['route']"
                                                class="font-normal w-full h-20 flex justify-center items-center text-center"
                                                (click)="this.serviceSettings.changeSetting(setting['id'], parent['id'])"
                                                routerLink="{{ setting['route'] }}">
                                            <p [class.font-medium]="this.serviceSettings.getSelectedSetting() === setting['id']" class="m-0">
                                                {{ setting['label'] | translate }}
                                            </p>
                                        </button>
                                    </mat-panel-title>
                                </mat-expansion-panel-header>
                                <div *ngFor="let action of this.serviceSettings.getSettingsAction(setting['id'])"
                                     [class.border-gray-600]="!action['showOnlyIfActive']"
                                     [class.border-t]="!action['showOnlyIfActive']"
                                     [class.w-full]="!action['showOnlyIfActive']">
                                    <div class="border-b border-gray-400"
                                         *ngIf="(this.privilegesService.hasPrivilege(action['privilege']) || setting['privilege'] == '*') && (!action['showOnlyIfActive'] || (action['showOnlyIfActive'] && this.router.url.includes(action['route'])))">
                                        <button mat-button
                                                [class.text-green-400]="this.router.url.includes(action['route'])"
                                                class="font-normal w-full h-12 ml-12 flex items-center text-center"
                                                (click)="this.serviceSettings.changeSetting(setting['id'], parent['id'])"
                                                routerLink="{{ action['route'] }}"
                                                [class.disable_link]="action['showOnlyIfActive']">
                                            <i class="absolute text-lg w-10 h-10 rounded-full flex items-center justify-center {{action['icon']}}"></i>
                                            <p class="m-0 ml-12" style="margin-top: 2.5px!important">
                                                {{ action['label'] | translate }}
                                            </p>
                                        </button>
                                    </div>
                                </div>
                            </mat-expansion-panel>
                        </div>
                        <ng-template #noActions>
                            <button *ngIf="this.privilegesService.hasPrivilege(setting['privilege']) || setting['privilege'] == '*'"
                                    mat-button [class.text-green-400]="this.router.url == setting['route']"
                                    class="font-normal w-full h-20 flex justify-center items-center text-center"
                                    (click)="this.serviceSettings.changeSetting(setting['id'], parent['id'])"
                                    routerLink="{{ setting['route'] }}">
                                <i class="absolute left-4 w-10 h-10 rounded-full flex items-center justify-center fa-lg {{setting['icon']}}"></i>
                                <p [class.font-medium]="this.serviceSettings.getSelectedSetting() === setting['id']" class="m-0">
                                    {{ setting['label'] | translate }}
                                </p>
                            </button>
                        </ng-template>
                    </div>
                </div>
            </mat-expansion-panel>
        </mat-nav-list>
    </mat-sidenav>
    <mat-sidenav-content class="bg-white">
        <div class="settings_header">
            <button mat-icon-button
                    (click)="sidenav.toggle(); this.serviceSettings.toggleMenu();" class="absolute left-2 top-2">
                <i [class.fa-arrow-right]="!this.serviceSettings.getIsMenuOpen()" class="fas fa-arrow-left text-2xl"></i>
            </button>
            <div class="settings_title text-center">
                <h3>{{ this.serviceSettings.getTitle() }}</h3>
                <hr class="border-green-400">
            </div>
        </div>
    </mat-sidenav-content>
</mat-sidenav-container>
