// frontend/src/pages/upload.tsx
/** This file is part of Open-Capture.

 Open-Capture is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.
 Open-Capture is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Open-Capture. If not, see <https://www.gnu.org/licenses/gpl-3.0.html>.

 @dev : Nathan CHEVAL <nathan.cheval@edissyum.com> */

import { t } from "i18next";
import { useEffect, useState } from "react";
import { Check, Wrench } from "lucide-react";

import { useUser } from "../services/hooks/useUser";
import { axiosApiCall } from "../services/hooks/axiosApiCall";

import { Button } from "../components/Button";
import { Loader } from "../components/loader/Loader";
import { showToast } from "../components/ToastProvider";
import UploadDropzone from "../components/upload/Dropzone";

export function UploadPage() {
    const { get, post } = axiosApiCall();
    const { user, loadingUser } = useUser();

    const [module, setModule] = useState("");

    const [timeout, setTimeout] = useState(2000);

    const [workflows, setWorkflows] = useState<any[]>([]);
    const [workflowLoading, setWorkflowLoading] = useState(false);
    const [selectedWorkflow, setSelectedWorkflow] = useState<any>(null);

    const [files, setFiles] = useState<File[]>([]);
    const [sending, setSending] = useState(false);
    const [completedFiles, setCompletedFiles] = useState<string[]>([]);
    const [progress, setProgress] = useState<Record<string, number | undefined>>({});
    const workflowTooltipMinLength = 40;

    const selectedModule = localStorage.getItem('selectedModule');
    if (selectedModule && selectedModule !== module) {
        setModule(selectedModule);
    }

    useEffect(() => {
        const handler = () => {
            const module = localStorage.getItem('selectedModule');
            if (module) {
                setFiles([]);
                setModule(module);
                setWorkflows([]);
                setSelectedWorkflow(null);
            }
        };

        window.addEventListener("updateModule", handler);
        return () => window.removeEventListener("updateModule", handler);
    }, []);

    // Retrieve timeout setting
    useEffect(() => {
        const retrieveTimeout = async () => {
            try {
                get(`config/getConfigurationNoAuth/timeoutUpload`).then((response) => {
                    if (response && response.configuration && response.configuration.length > 0) {
                        setTimeout(response.configuration[0].data.value);
                    }
                });
            } catch (error) {
                console.error("Error retrieving timeout:", error);
            }
        }

        retrieveTimeout().then();
    }, []);

    // Retrieve workflows list
    useEffect(() => {
        if (loadingUser || !selectedModule) return;

        const retrieveWorkflows = async () => {
            setWorkflowLoading(true);
            try {
                get(`workflows/${ selectedModule }/list/user/${ user.id }`).then((response) => {
                    setWorkflows(response.workflows);
                    setWorkflowLoading(false);
                });
            } catch (error) {
                console.error("Error retrieving workflows:", error);
            }
        }

        retrieveWorkflows().then();
    }, [loadingUser, selectedModule]);

    const handleUpload = async () => {
        if (files.length === 0 || !selectedWorkflow) return;

        setSending(true);
        const res = await checkFiles(files);
        if (res !== undefined) {
            await upload(files);
        }
        setSending(false);
    };

    async function upload(filesToUpload: any[]) {
        let cpt = 0;
        for (const file of filesToUpload) {
            const formData = new FormData();
            formData.append("files", file);
            formData.append("userId", user.id);
            formData.append("workflowId", selectedWorkflow);

            try {
                await post(`/${ module }/upload`, formData, {
                    headers: {
                        "Content-Type": "multipart/form-data",
                    },
                    onUploadProgress: (progressEvent) => {
                        setProgress((prev) => ({
                            ...prev,
                            [file.id]: progressEvent
                        }));
                    }
                });
                setCompletedFiles(prev => [...prev, file.id]);
                cpt += 1;
                if (cpt === filesToUpload.length) {
                    setFiles([]);
                    showToast(t('UPLOAD.upload_success', { count: filesToUpload.length }), "success");
                }
            } catch (error) {
                setProgress((prev => ({
                    ...prev,
                    [file.name]: undefined
                })));
                console.error("Error upload file:", error);
            }
        }
    }

    async function checkFiles(filesToCheck: File[]) {
        const formData = new FormData();
        for (const file of filesToCheck) {
            formData.append("files", file);
        }

        try {
            return await post("/checkFileBeforeUpload", formData, {
                headers: {
                    "Content-Type": "multipart/form-data",
                },
                timeout: timeout
            });
        } catch (error) {
            console.error("Error checking files before upload:", error);
        }
    }

    return (
        <div className='flex h-full w-full overflow-hidden'>
            <div className='pb-20 h-full w-[350px] shrink-0 border-r border-(--border-secondary) bg-(--bg-primary)'>
                <h1 className='px-6 pt-6 text-xl font-bold mb-4 truncate flex items-center gap-2'>
                    <Wrench size={ 20 } className='text-(--color-primary)'/>
                    { t('UPLOAD.select_workflows') }
                </h1>
                <div className='px-6 flex flex-col gap-2 overflow-y-auto h-full'>
                    {
                        workflowLoading && (
                            <Loader/>
                        )
                    }
                    { workflows.map((workflow) => (
                        <div key={ workflow.id }
                             onClick={ () => setSelectedWorkflow(workflow.workflow_id) }
                             { ...(workflow.label.length > workflowTooltipMinLength && {
                                 "data-tooltip-id": "tooltip",
                                 "data-tooltip-content": workflow.label
                             }) }
                             className={ `cursor-pointer flex items-center gap-1 border border-(--border-secondary)
                                          rounded-md p-2 hover:border-(--border-primary)
                                          ${ selectedWorkflow === workflow.workflow_id ? 'text-(--color-primary) border-(--color-primary) font-semibold bg-(--bg-selected)' : '' }` }>
                            { selectedWorkflow === workflow.workflow_id && (
                                <Check size={ 18 } className='shrink-0'/>
                            ) }
                            <p className='truncate'>{ workflow.label }</p>
                        </div>
                    )) }
                </div>
            </div>
            <div className='p-6 w-full flex flex-col h-full overflow-auto gap-4'>
                <div>
                    <h1 className='text-lg font-bold'>
                        { t('UPLOAD.upload') }
                    </h1>
                    <p className='text-(--text-secondary)'>
                        { t('UPLOAD.upload_hint') }
                    </p>
                </div>
                <UploadDropzone
                    accept={ {
                        "application/*": [".pdf"],
                        "image/*": [".jpg", ".jpeg", ".png", ".heif", ".heic"]
                    } }
                    progressByFile={ progress }
                    completedFiles={ completedFiles }
                    onFilesAccepted={ setFiles }
                    maxSize={ 10 * 1024 * 1024 }
                    className="bg-(--bg-primary)"
                />
                <div className="w-fit">
                    <Button onClick={ handleUpload }
                            disabled={ files.length === 0 || !selectedWorkflow || sending }>
                        { t('UPLOAD.upload_files', { count: files.length }) }
                    </Button>
                </div>
            </div>
        </div>
    );
}

// src/frontend/app/upload/upload.component.ts
/** This file is part of Open-Capture.

Open-Capture is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Open-Capture is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Open-Capture. If not, see <https://www.gnu.org/licenses/gpl-3.0.html>.

@dev : Nathan Cheval <nathan.cheval@outlook.fr> */

import { Component, OnInit, ViewEncapsulation } from '@angular/core';
import { FormControl } from "@angular/forms";
import { FileValidators } from "ngx-file-drag-drop";
import { environment } from  "../env";
import { catchError, finalize, tap } from "rxjs/operators";
import { of } from "rxjs";
import { HttpClient, HttpHeaders} from "@angular/common/http";
import { AuthService } from "../../services/auth.service";
import { UserService } from "../../services/user.service";
import { TranslateService } from "@ngx-translate/core";
import { NotificationService } from "../../services/notifications/notifications.service";
import { SessionStorageService } from "../../services/session-storage.service";

@Component({
    selector: 'app-upload',
    templateUrl: './upload.component.html',
    styleUrls: ['./upload.component.scss'],
    encapsulation: ViewEncapsulation.None
})

export class UploadComponent implements OnInit {
    allowedExtensions           : string[]      = ['pdf', 'jpg', 'jpeg', 'png', 'heif', 'heic'];
    headers                     : HttpHeaders   = this.authService.headers;
    selectedWorkflow            : any           = '';
    selectedWorkflowTechnicalId : any           = '';
    workflows                   : any[]         = [];
    loading                     : boolean       = true;
    sending                     : boolean       = false;
    error                       : boolean       = false;

    constructor(
        private http: HttpClient,
        public userService: UserService,
        private authService: AuthService,
        public translate: TranslateService,
        private notify: NotificationService,
        public sessionStorageService: SessionStorageService
    ) {}

    fileControl = new FormControl(
        [],
        [
            FileValidators.required,
            FileValidators.fileExtension(this.allowedExtensions)
        ]
    );

    ngOnInit(): void {
        if (!this.authService.headersExists) {
            this.authService.generateHeaders();
        }
        if (!this.userService.user.id) {
            this.userService.user = this.userService.getUserFromLocal();
        }

        const splitterOrVerifier: any = this.sessionStorageService.get('splitter_or_verifier');
        if (splitterOrVerifier !== undefined || splitterOrVerifier !== '') {
            this.getWorkflows(splitterOrVerifier);
        }
    }

    getWorkflows(splitterOrVerifier: string): void {
        this.http.get(environment['url'] + '/ws/workflows/' + splitterOrVerifier + '/list/user/' + this.userService.user.id, {headers: this.authService.headers}).pipe(
            tap((data: any) => {
                data.workflows.forEach((element: any, index: number) => {
                    let show = true;

                    if (element.process && element.process['api_only']) {
                        show = false
                    }

                    if (show) {
                        this.workflows.push(element);
                    }
                });

                if (this.workflows.length === 1) {
                    this.selectedWorkflow = data.workflows[0].id;
                    this.selectedWorkflowTechnicalId = data.workflows[0].workflow_id;
                }
            }),
            finalize(() => {this.loading = false;}),
            catchError((err: any) => {
                console.debug(err);
                this.notify.handleErrors(err);
                return of(false);
            })
        ).subscribe();
    }

    checkFile(data: any): void {
        this.error = false;
        if (data && data.length !== 0) {
            for (let i = 0; i < data.length; i++) {
                const fileExtension = data[i].name.split('.').pop();
                if (this.allowedExtensions.indexOf(fileExtension.toLowerCase()) === -1) {
                    this.error = true;
                    this.notify.handleErrors(this.translate.instant('UPLOAD.extension_unauthorized'));
                    return;
                }
            }
        }
    }

    setWorkflow(workflowId: any) {
        this.workflows.forEach((element: any) => {
            if (element.id === workflowId) {
                this.selectedWorkflowTechnicalId = element.workflow_id;
            }
        });
        this.selectedWorkflow = workflowId;
    }

    uploadFile(): void {
        this.sending = true;
        const formData: FormData = new FormData();
        if (this.fileControl.value!.length === 0) {
            this.notify.handleErrors(this.translate.instant('UPLOAD.no_file'));
            return;
        }

        let timeout = 2000;
        for (let i = 0; i < this.fileControl.value!.length; i++) {
            if (this.fileControl.status === 'VALID') {
                timeout += this.fileControl.value![i]['size'] / 200;
                formData.append(this.fileControl.value![i]['name'], this.fileControl.value![i]);
            } else {
                this.notify.handleErrors(this.translate.instant('UPLOAD.extension_unauthorized'));
                return;
            }
        }

        formData.set('userId', this.userService.user.id);
        formData.set('workflowId', this.selectedWorkflowTechnicalId);

        const splitterOrVerifier = this.sessionStorageService.get('splitter_or_verifier');
        if (splitterOrVerifier !== undefined || splitterOrVerifier !== '') {
            this.http.post(
                environment['url'] + '/ws/checkFileBeforeUpload', formData, {headers: new HttpHeaders({ timeout: `${timeout}` })},
            ).pipe(
                tap(() => {
                    this.http.post(environment['url'] + '/ws/' + splitterOrVerifier + '/upload', formData, {headers: this.authService.headers}).pipe(
                        tap(() => {
                            this.sending = false;
                            this.fileControl.setValue([]);
                            this.notify.success(this.translate.instant('UPLOAD.upload_success'));
                        }),
                        catchError((err: any) => {
                            this.sending = false;
                            this.fileControl.setValue([]);
                            this.notify.handleErrors(err);
                            return of(false);
                        })
                    ).subscribe();
                }),
                catchError((err: any) => {
                    this.sending = false;
                    this.fileControl.setValue([]);
                    this.notify.handleErrors(this.translate.instant('ERROR.permission_problem'));
                    return of(false);
                })
            ).subscribe();
        } else {
            this.notify.handleErrors(this.translate.instant('ERROR.unknow_error'));
        }
    }
}

<mat-sidenav-container class="absolute left-0 right-0 bottom-0" style="top: 4.1rem" [autosize]="true">
    <mat-sidenav #sidenav mode="side" [opened]="true" class="2xl:w-96 xl:w-80 md:w-72 sm:w-64 w-32 flex flex-col h-full border-r border-green-400" style="top:0.1rem">
        <h3 class="text-center text-gray-900 m-0 h-16" style="padding-top: 1.2rem">
            {{ "ACCOUNTS.choose_workflow_upload" | translate }}
        </h3>
        <mat-divider></mat-divider>
        <mat-list class="h-full-overflow overflow-auto">
            @for (workflow of workflows; track workflow.id) {
                <span class="flex">
                    <mat-list-item class="cursor-pointer m-2 w-auto pr-1" (click)="setWorkflow(workflow.id)">
                        <span [class.text-green-400]="this.selectedWorkflow === workflow.id" class="hover:text-green-400"
                              [matTooltip]="workflow.label" [matTooltipDisabled]="workflow.label.replace(' ', '').length <= 30">
                            {{ workflow.label }}
                        </span>
                    </mat-list-item>
                    <span class="flex">
                        @if (this.selectedWorkflow === workflow.id) {
                            <i class="text-lg fa-regular fa-circle-check text-green-400 mr-4 content-center"></i>
                        }
                    </span>
                </span>
            }
        </mat-list>
    </mat-sidenav>
    <mat-sidenav-content class="bg-white overflow-hidden">
        <button mat-icon-button (click)="sidenav.toggle();" class="absolute left-2 top-2 z-30">
            <i [class.transform]="!sidenav.opened" [class.rotate-180]="!sidenav.opened" class="fa-solid fa-stream text-xl text-gray-900"></i>
        </button>
        @if (this.loading) {
            <div>
                <app-loader></app-loader>
            </div>
        }
        <ngx-file-drag-drop
                [class.pointer-events-none]="this.sending"
                [class.disabled]="this.sending"
                [formControl]="fileControl"
                [activeBorderColor]="'#97BF3D'"
                [multiple]="true"
                [accept]="'pdf'"
                [displayFileSize]="true"
                [emptyPlaceholder]="'UPLOAD.placeholder' | translate"
                [class]="'max-w-3xl h-56 mt-24 mb-5 overflow-y-scroll'"
                (valueChanged)="checkFile($event)">
        </ngx-file-drag-drop>
        <div class="text-center" [class.cursor-not-allowed]="this.error || !(!this.sending && this.fileControl.value!.length !== 0)">
            <button mat-button
                    [disabled]="this.error || this.sending || (this.selectedWorkflow === '') || this.fileControl.value!.length === 0" (click)="uploadFile()"
                    [class.bg-opacity-100]="!this.error && !this.sending && this.selectedWorkflow && this.fileControl.value!.length !== 0"
                    [class.bg-green-400]="!this.error && !this.sending && this.selectedWorkflow && this.fileControl.value!.length !== 0"
                    [class.bg-gray-400]="this.error || !(!this.sending && this.selectedWorkflow && this.fileControl.value!.length !== 0)"
                    class="p-6 mr-4 border min-w-56 text-white transition border-solid duration-300 border-green-400 hover:text-gray-900 hover:bg-transparent">
                {{ 'UPLOAD.upload_file' | translate }}
            </button>
        </div>
        @if (this.selectedWorkflow === '') {
            <span class="flex justify-center mt-4 text-red-500">
                {{ 'UPLOAD.please_select_workflow' | translate }}
            </span>
        }
    </mat-sidenav-content>
</mat-sidenav-container>
