// frontend/src/services/hooks/ConfirmDialog.tsx
/** This file is part of Open-Capture.

 Open-Capture is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 Open-Capture is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Open-Capture. If not, see <https://www.gnu.org/licenses/gpl-3.0.html>.

 @dev : Nathan CHEVAL <nathan.cheval@edissyum.com> */

import React from "react";
import { t } from "i18next";
import { confirmDialog } from 'primereact/confirmdialog';

export function showConfirmDialog({
    title,
    message,
    icon,
    cancelText = t('GLOBAL.cancel'),
    confirmText = t('GLOBAL.yes'),
    onConfirm,
    onCancel
}: {
    title: string;
    message: string;
    icon?: React.ReactNode;
    cancelText?: string;
    confirmText?: string;
    onConfirm: () => void;
    onCancel: () => void;
}) {
    confirmDialog({
        message: message,
        header: title,
        icon: icon,
        acceptLabel: confirmText,
        rejectLabel: cancelText,
        acceptClassName: "outline-none! shadow-none! bg-(--color-primary)! border-2! border-(--border-primary)! text-white! hover:bg-(--color-primary)/10! hover:text-(--color-primary)!",
        rejectClassName: "outline-none! shadow-none! bg-transparent! text-(--text-secondary)! border-2! border-transparent! hover:border-2! hover:border-(--text-secondary)!",
        accept() {
            onConfirm();
        },
        reject() {
            onCancel();
        }
    })
}

// src/frontend/services/confirm-dialog/confirm-dialog.component.ts
/** This file is part of Open-Capture.

 Open-Capture is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 Open-Capture is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Open-Capture. If not, see <https://www.gnu.org/licenses/gpl-3.0.html>.

 @dev : Nathan Cheval <nathan.cheval@outlook.fr> */

import { Component, Inject } from '@angular/core';
import { MAT_DIALOG_DATA } from "@angular/material/dialog";

export interface ConfirmData {
    confirmTitle : string
    confirmText : string
    confirmButton : string
    selectValues: any
    selectLabel : string
    confirmButtonColor : string
    cancelButton : string
}

@Component({
    selector: 'app-confirm-dialog',
    templateUrl: './confirm-dialog.component.html'
})

export class ConfirmDialogComponent {
    selectData: any;

    constructor(
        @Inject(MAT_DIALOG_DATA) public data: ConfirmData
    ) {}
}

<h2 mat-dialog-title>{{ data.confirmTitle }}</h2>
<hr class="border-green-400 -mt-4 w-11/12 m-auto">
<mat-dialog-content class="mat-typography text-gray-900" [innerHTML]=data.confirmText></mat-dialog-content>
@if (data.selectValues) {
    <mat-dialog-content class="mat-typography">
        <mat-form-field class="w-full mt-1">
            <mat-label>{{ data.selectLabel }}</mat-label>
            <mat-select [(value)]="this.selectData">
                @for (option of data.selectValues; track option['id']) {
                    <mat-option [value]="option['id']">{{ option['label'] }}</mat-option>
                }
            </mat-select>
        </mat-form-field>
    </mat-dialog-content>
}
@if (data.askNewId) {
    <form class="flex justify-center">
        <mat-form-field class="w-10/12 -mb-5">
            <mat-label>{{ data.askNewIdLabel }}</mat-label>
            <input matInput [(ngModel)]="data.newId" [ngModelOptions]="{standalone: true}"/>
        </mat-form-field>
    </form>
}
<mat-dialog-actions class="flex justify-end pb-4 pr-4">
    <button mat-button [mat-dialog-close]="">{{ data.cancelButton }}</button>
    @if (data.selectValues) {
        <button mat-button [mat-dialog-close]="this.selectData" color="{{ data.confirmButtonColor }}" cdkFocusInitial>{{ data.confirmButton }}</button>
    } @else if (data.askNewId) {
        <button mat-button [mat-dialog-close]="this.data" color="{{ data.confirmButtonColor }}" cdkFocusInitial>{{ data.confirmButton }}</button>
    } @else {
        <button mat-button [mat-dialog-close]="true" color="{{ data.confirmButtonColor }}" cdkFocusInitial [class.text-green-400]="data.confirmButtonColor === 'green'">
            {{ data.confirmButton }}
        </button>
    }
</mat-dialog-actions>
